/*
 * Expense Reports
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AttachmentFolderModel;
import com.konfigthis.client.model.ObjectAccessModel;
import com.konfigthis.client.model.ProjectModel;
import com.konfigthis.client.model.StateCountryModel;
import com.konfigthis.client.model.UserGroupModel;
import com.konfigthis.client.model.UserModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AttachmentModel
 */
public class AttachmentModelTest {
    private final AttachmentModel model = new AttachmentModel();

    /**
     * Model tests for AttachmentModel
     */
    @Test
    public void testAttachmentModel() {
        // TODO: test AttachmentModel
    }

    /**
     * Test the property 'access'
     */
    @Test
    public void accessTest() {
        // TODO: test access
    }

    /**
     * Test the property 'annId'
     */
    @Test
    public void annIdTest() {
        // TODO: test annId
    }

    /**
     * Test the property 'appraisalAssignmentId'
     */
    @Test
    public void appraisalAssignmentIdTest() {
        // TODO: test appraisalAssignmentId
    }

    /**
     * Test the property 'appraisalItemResponseId'
     */
    @Test
    public void appraisalItemResponseIdTest() {
        // TODO: test appraisalItemResponseId
    }

    /**
     * Test the property 'appraisalid'
     */
    @Test
    public void appraisalidTest() {
        // TODO: test appraisalid
    }

    /**
     * Test the property 'assetid'
     */
    @Test
    public void assetidTest() {
        // TODO: test assetid
    }

    /**
     * Test the property 'atchType'
     */
    @Test
    public void atchTypeTest() {
        // TODO: test atchType
    }

    /**
     * Test the property 'attachUserModel'
     */
    @Test
    public void attachUserModelTest() {
        // TODO: test attachUserModel
    }

    /**
     * Test the property 'attachid'
     */
    @Test
    public void attachidTest() {
        // TODO: test attachid
    }

    /**
     * Test the property 'attachmentFolderModel'
     */
    @Test
    public void attachmentFolderModelTest() {
        // TODO: test attachmentFolderModel
    }

    /**
     * Test the property 'authkey'
     */
    @Test
    public void authkeyTest() {
        // TODO: test authkey
    }

    /**
     * Test the property 'candidateAccess'
     */
    @Test
    public void candidateAccessTest() {
        // TODO: test candidateAccess
    }

    /**
     * Test the property 'candidateid'
     */
    @Test
    public void candidateidTest() {
        // TODO: test candidateid
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'cid'
     */
    @Test
    public void cidTest() {
        // TODO: test cid
    }

    /**
     * Test the property 'comments'
     */
    @Test
    public void commentsTest() {
        // TODO: test comments
    }

    /**
     * Test the property 'createts'
     */
    @Test
    public void createtsTest() {
        // TODO: test createts
    }

    /**
     * Test the property 'createuserid'
     */
    @Test
    public void createuseridTest() {
        // TODO: test createuserid
    }

    /**
     * Test the property 'customerId'
     */
    @Test
    public void customerIdTest() {
        // TODO: test customerId
    }

    /**
     * Test the property 'dLExpiryDate'
     */
    @Test
    public void dLExpiryDateTest() {
        // TODO: test dLExpiryDate
    }

    /**
     * Test the property 'dLIssueDate'
     */
    @Test
    public void dLIssueDateTest() {
        // TODO: test dLIssueDate
    }

    /**
     * Test the property 'documentContent'
     */
    @Test
    public void documentContentTest() {
        // TODO: test documentContent
    }

    /**
     * Test the property 'documentExpiryDate'
     */
    @Test
    public void documentExpiryDateTest() {
        // TODO: test documentExpiryDate
    }

    /**
     * Test the property 'documentType'
     */
    @Test
    public void documentTypeTest() {
        // TODO: test documentType
    }

    /**
     * Test the property 'documnetIssueDate'
     */
    @Test
    public void documnetIssueDateTest() {
        // TODO: test documnetIssueDate
    }

    /**
     * Test the property 'expenseItemId'
     */
    @Test
    public void expenseItemIdTest() {
        // TODO: test expenseItemId
    }

    /**
     * Test the property 'expenseid'
     */
    @Test
    public void expenseidTest() {
        // TODO: test expenseid
    }

    /**
     * Test the property 'fileExtn'
     */
    @Test
    public void fileExtnTest() {
        // TODO: test fileExtn
    }

    /**
     * Test the property 'filename'
     */
    @Test
    public void filenameTest() {
        // TODO: test filename
    }

    /**
     * Test the property 'folder'
     */
    @Test
    public void folderTest() {
        // TODO: test folder
    }

    /**
     * Test the property 'folderId'
     */
    @Test
    public void folderIdTest() {
        // TODO: test folderId
    }

    /**
     * Test the property 'global'
     */
    @Test
    public void globalTest() {
        // TODO: test global
    }

    /**
     * Test the property 'goalid'
     */
    @Test
    public void goalidTest() {
        // TODO: test goalid
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'leaveid'
     */
    @Test
    public void leaveidTest() {
        // TODO: test leaveid
    }

    /**
     * Test the property 'multiSigning'
     */
    @Test
    public void multiSigningTest() {
        // TODO: test multiSigning
    }

    /**
     * Test the property 'objectAccessModelList'
     */
    @Test
    public void objectAccessModelListTest() {
        // TODO: test objectAccessModelList
    }

    /**
     * Test the property 'objectType'
     */
    @Test
    public void objectTypeTest() {
        // TODO: test objectType
    }

    /**
     * Test the property 'obtype'
     */
    @Test
    public void obtypeTest() {
        // TODO: test obtype
    }

    /**
     * Test the property 'payStubId'
     */
    @Test
    public void payStubIdTest() {
        // TODO: test payStubId
    }

    /**
     * Test the property 'positionid'
     */
    @Test
    public void positionidTest() {
        // TODO: test positionid
    }

    /**
     * Test the property 'projectModel'
     */
    @Test
    public void projectModelTest() {
        // TODO: test projectModel
    }

    /**
     * Test the property 'projectid'
     */
    @Test
    public void projectidTest() {
        // TODO: test projectid
    }

    /**
     * Test the property 'resume'
     */
    @Test
    public void resumeTest() {
        // TODO: test resume
    }

    /**
     * Test the property 'ruleid'
     */
    @Test
    public void ruleidTest() {
        // TODO: test ruleid
    }

    /**
     * Test the property 's3id'
     */
    @Test
    public void s3idTest() {
        // TODO: test s3id
    }

    /**
     * Test the property 'signNowDocId'
     */
    @Test
    public void signNowDocIdTest() {
        // TODO: test signNowDocId
    }

    /**
     * Test the property 'signNowTemplateId'
     */
    @Test
    public void signNowTemplateIdTest() {
        // TODO: test signNowTemplateId
    }

    /**
     * Test the property 'signStatus'
     */
    @Test
    public void signStatusTest() {
        // TODO: test signStatus
    }

    /**
     * Test the property 'signatureId'
     */
    @Test
    public void signatureIdTest() {
        // TODO: test signatureId
    }

    /**
     * Test the property 'signatureRequestId'
     */
    @Test
    public void signatureRequestIdTest() {
        // TODO: test signatureRequestId
    }

    /**
     * Test the property 'signingDate'
     */
    @Test
    public void signingDateTest() {
        // TODO: test signingDate
    }

    /**
     * Test the property 'size'
     */
    @Test
    public void sizeTest() {
        // TODO: test size
    }

    /**
     * Test the property 'skilluserId'
     */
    @Test
    public void skilluserIdTest() {
        // TODO: test skilluserId
    }

    /**
     * Test the property 'stateCountryModel'
     */
    @Test
    public void stateCountryModelTest() {
        // TODO: test stateCountryModel
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'taskId'
     */
    @Test
    public void taskIdTest() {
        // TODO: test taskId
    }

    /**
     * Test the property 'ticketId'
     */
    @Test
    public void ticketIdTest() {
        // TODO: test ticketId
    }

    /**
     * Test the property 'timecardid'
     */
    @Test
    public void timecardidTest() {
        // TODO: test timecardid
    }

    /**
     * Test the property 'topic'
     */
    @Test
    public void topicTest() {
        // TODO: test topic
    }

    /**
     * Test the property 'trainingId'
     */
    @Test
    public void trainingIdTest() {
        // TODO: test trainingId
    }

    /**
     * Test the property 'userAccess'
     */
    @Test
    public void userAccessTest() {
        // TODO: test userAccess
    }

    /**
     * Test the property 'userGroupModel'
     */
    @Test
    public void userGroupModelTest() {
        // TODO: test userGroupModel
    }

    /**
     * Test the property 'userModel'
     */
    @Test
    public void userModelTest() {
        // TODO: test userModel
    }

    /**
     * Test the property 'userid'
     */
    @Test
    public void useridTest() {
        // TODO: test userid
    }

}
