/*
 * Expense Reports
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CandidatesGetBasicDetailsResponseDataInner
 */
public class CandidatesGetBasicDetailsResponseDataInnerTest {
    private final CandidatesGetBasicDetailsResponseDataInner model = new CandidatesGetBasicDetailsResponseDataInner();

    /**
     * Model tests for CandidatesGetBasicDetailsResponseDataInner
     */
    @Test
    public void testCandidatesGetBasicDetailsResponseDataInner() {
        // TODO: test CandidatesGetBasicDetailsResponseDataInner
    }

    /**
     * Test the property 'recruitId'
     */
    @Test
    public void recruitIdTest() {
        // TODO: test recruitId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'dateOfBirth'
     */
    @Test
    public void dateOfBirthTest() {
        // TODO: test dateOfBirth
    }

    /**
     * Test the property 'statusid'
     */
    @Test
    public void statusidTest() {
        // TODO: test statusid
    }

    /**
     * Test the property 'referrerId'
     */
    @Test
    public void referrerIdTest() {
        // TODO: test referrerId
    }

    /**
     * Test the property 'createts'
     */
    @Test
    public void createtsTest() {
        // TODO: test createts
    }

    /**
     * Test the property 'notes'
     */
    @Test
    public void notesTest() {
        // TODO: test notes
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'userid'
     */
    @Test
    public void useridTest() {
        // TODO: test userid
    }

    /**
     * Test the property 'recruiterUserId'
     */
    @Test
    public void recruiterUserIdTest() {
        // TODO: test recruiterUserId
    }

    /**
     * Test the property 'summaryByCandidate'
     */
    @Test
    public void summaryByCandidateTest() {
        // TODO: test summaryByCandidate
    }

    /**
     * Test the property 'candidateLock'
     */
    @Test
    public void candidateLockTest() {
        // TODO: test candidateLock
    }

    /**
     * Test the property 'educationStr'
     */
    @Test
    public void educationStrTest() {
        // TODO: test educationStr
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'appliedPositions'
     */
    @Test
    public void appliedPositionsTest() {
        // TODO: test appliedPositions
    }

    /**
     * Test the property 'updatedOn'
     */
    @Test
    public void updatedOnTest() {
        // TODO: test updatedOn
    }

    /**
     * Test the property 'cid'
     */
    @Test
    public void cidTest() {
        // TODO: test cid
    }

    /**
     * Test the property 'tagIds'
     */
    @Test
    public void tagIdsTest() {
        // TODO: test tagIds
    }

    /**
     * Test the property 'statusColor'
     */
    @Test
    public void statusColorTest() {
        // TODO: test statusColor
    }

    /**
     * Test the property 'appliedPositionIds'
     */
    @Test
    public void appliedPositionIdsTest() {
        // TODO: test appliedPositionIds
    }

    /**
     * Test the property 'appliedPositionUids'
     */
    @Test
    public void appliedPositionUidsTest() {
        // TODO: test appliedPositionUids
    }

    /**
     * Test the property 'recruiterThumbnail'
     */
    @Test
    public void recruiterThumbnailTest() {
        // TODO: test recruiterThumbnail
    }

    /**
     * Test the property 'recruiterName'
     */
    @Test
    public void recruiterNameTest() {
        // TODO: test recruiterName
    }

    /**
     * Test the property 'recruiterGender'
     */
    @Test
    public void recruiterGenderTest() {
        // TODO: test recruiterGender
    }

    /**
     * Test the property 'referrerName'
     */
    @Test
    public void referrerNameTest() {
        // TODO: test referrerName
    }

    /**
     * Test the property 'isInternalCand'
     */
    @Test
    public void isInternalCandTest() {
        // TODO: test isInternalCand
    }

    /**
     * Test the property 'applicationStatus'
     */
    @Test
    public void applicationStatusTest() {
        // TODO: test applicationStatus
    }

    /**
     * Test the property 'verified'
     */
    @Test
    public void verifiedTest() {
        // TODO: test verified
    }

    /**
     * Test the property 'positionNameList'
     */
    @Test
    public void positionNameListTest() {
        // TODO: test positionNameList
    }

    /**
     * Test the property 'internalCandidate'
     */
    @Test
    public void internalCandidateTest() {
        // TODO: test internalCandidate
    }

}
