/*
 * Expense Reports
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CustomFieldStyleModel
 */
public class CustomFieldStyleModelTest {
    private final CustomFieldStyleModel model = new CustomFieldStyleModel();

    /**
     * Model tests for CustomFieldStyleModel
     */
    @Test
    public void testCustomFieldStyleModel() {
        // TODO: test CustomFieldStyleModel
    }

    /**
     * Test the property 'bold'
     */
    @Test
    public void boldTest() {
        // TODO: test bold
    }

    /**
     * Test the property 'color'
     */
    @Test
    public void colorTest() {
        // TODO: test color
    }

    /**
     * Test the property 'italic'
     */
    @Test
    public void italicTest() {
        // TODO: test italic
    }

}
