/*
 * Expense Reports
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.UserViewModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DepartmentModel
 */
public class DepartmentModelTest {
    private final DepartmentModel model = new DepartmentModel();

    /**
     * Model tests for DepartmentModel
     */
    @Test
    public void testDepartmentModel() {
        // TODO: test DepartmentModel
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'cid'
     */
    @Test
    public void cidTest() {
        // TODO: test cid
    }

    /**
     * Test the property 'departmentCode'
     */
    @Test
    public void departmentCodeTest() {
        // TODO: test departmentCode
    }

    /**
     * Test the property 'departmentId'
     */
    @Test
    public void departmentIdTest() {
        // TODO: test departmentId
    }

    /**
     * Test the property 'departmentLabel'
     */
    @Test
    public void departmentLabelTest() {
        // TODO: test departmentLabel
    }

    /**
     * Test the property 'deptHead'
     */
    @Test
    public void deptHeadTest() {
        // TODO: test deptHead
    }

    /**
     * Test the property 'deptHeadName'
     */
    @Test
    public void deptHeadNameTest() {
        // TODO: test deptHeadName
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'noOfEmployees'
     */
    @Test
    public void noOfEmployeesTest() {
        // TODO: test noOfEmployees
    }

    /**
     * Test the property 'parentDepartmentId'
     */
    @Test
    public void parentDepartmentIdTest() {
        // TODO: test parentDepartmentId
    }

    /**
     * Test the property 'parentDepartmentName'
     */
    @Test
    public void parentDepartmentNameTest() {
        // TODO: test parentDepartmentName
    }

    /**
     * Test the property 'userModel'
     */
    @Test
    public void userModelTest() {
        // TODO: test userModel
    }

}
