/*
 * Expense Reports
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.UserGroupModel;
import com.konfigthis.client.model.UserModel;
import com.konfigthis.client.model.UserViewModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.sql.Timestamp;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DynaFormSlimModel
 */
public class DynaFormSlimModelTest {
    private final DynaFormSlimModel model = new DynaFormSlimModel();

    /**
     * Model tests for DynaFormSlimModel
     */
    @Test
    public void testDynaFormSlimModel() {
        // TODO: test DynaFormSlimModel
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'anonymous'
     */
    @Test
    public void anonymousTest() {
        // TODO: test anonymous
    }

    /**
     * Test the property 'attemptLimit'
     */
    @Test
    public void attemptLimitTest() {
        // TODO: test attemptLimit
    }

    /**
     * Test the property 'availability'
     */
    @Test
    public void availabilityTest() {
        // TODO: test availability
    }

    /**
     * Test the property 'cid'
     */
    @Test
    public void cidTest() {
        // TODO: test cid
    }

    /**
     * Test the property 'createUserModel'
     */
    @Test
    public void createUserModelTest() {
        // TODO: test createUserModel
    }

    /**
     * Test the property 'createUserViewModel'
     */
    @Test
    public void createUserViewModelTest() {
        // TODO: test createUserViewModel
    }

    /**
     * Test the property 'createts'
     */
    @Test
    public void createtsTest() {
        // TODO: test createts
    }

    /**
     * Test the property 'dataFlow'
     */
    @Test
    public void dataFlowTest() {
        // TODO: test dataFlow
    }

    /**
     * Test the property 'dynaFormCode'
     */
    @Test
    public void dynaFormCodeTest() {
        // TODO: test dynaFormCode
    }

    /**
     * Test the property 'dynamicFormId'
     */
    @Test
    public void dynamicFormIdTest() {
        // TODO: test dynamicFormId
    }

    /**
     * Test the property 'formType'
     */
    @Test
    public void formTypeTest() {
        // TODO: test formType
    }

    /**
     * Test the property 'layout'
     */
    @Test
    public void layoutTest() {
        // TODO: test layout
    }

    /**
     * Test the property 'mappedEntity'
     */
    @Test
    public void mappedEntityTest() {
        // TODO: test mappedEntity
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'presentationStyle'
     */
    @Test
    public void presentationStyleTest() {
        // TODO: test presentationStyle
    }

    /**
     * Test the property 'publicSummary'
     */
    @Test
    public void publicSummaryTest() {
        // TODO: test publicSummary
    }

    /**
     * Test the property 'secSequence'
     */
    @Test
    public void secSequenceTest() {
        // TODO: test secSequence
    }

    /**
     * Test the property 'showCorrect'
     */
    @Test
    public void showCorrectTest() {
        // TODO: test showCorrect
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'thresholdScore'
     */
    @Test
    public void thresholdScoreTest() {
        // TODO: test thresholdScore
    }

    /**
     * Test the property 'timeLimit'
     */
    @Test
    public void timeLimitTest() {
        // TODO: test timeLimit
    }

    /**
     * Test the property 'updatets'
     */
    @Test
    public void updatetsTest() {
        // TODO: test updatets
    }

    /**
     * Test the property 'userGroupModel'
     */
    @Test
    public void userGroupModelTest() {
        // TODO: test userGroupModel
    }

}
