/*
 * Expense Reports
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CandidateModel;
import com.konfigthis.client.model.DynaFormSectionAssignmentModel;
import com.konfigthis.client.model.DynaFormSlimModel;
import com.konfigthis.client.model.UserModel;
import com.konfigthis.client.model.UserViewModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DynamicFormAssignmentModel
 */
public class DynamicFormAssignmentModelTest {
    private final DynamicFormAssignmentModel model = new DynamicFormAssignmentModel();

    /**
     * Model tests for DynamicFormAssignmentModel
     */
    @Test
    public void testDynamicFormAssignmentModel() {
        // TODO: test DynamicFormAssignmentModel
    }

    /**
     * Test the property 'allowGrader'
     */
    @Test
    public void allowGraderTest() {
        // TODO: test allowGrader
    }

    /**
     * Test the property 'assessmentScore'
     */
    @Test
    public void assessmentScoreTest() {
        // TODO: test assessmentScore
    }

    /**
     * Test the property 'assignCandidateModel'
     */
    @Test
    public void assignCandidateModelTest() {
        // TODO: test assignCandidateModel
    }

    /**
     * Test the property 'assignUserModel'
     */
    @Test
    public void assignUserModelTest() {
        // TODO: test assignUserModel
    }

    /**
     * Test the property 'assignUserViewModel'
     */
    @Test
    public void assignUserViewModelTest() {
        // TODO: test assignUserViewModel
    }

    /**
     * Test the property 'assignmentId'
     */
    @Test
    public void assignmentIdTest() {
        // TODO: test assignmentId
    }

    /**
     * Test the property 'cid'
     */
    @Test
    public void cidTest() {
        // TODO: test cid
    }

    /**
     * Test the property 'createUserModel'
     */
    @Test
    public void createUserModelTest() {
        // TODO: test createUserModel
    }

    /**
     * Test the property 'createUserViewModel'
     */
    @Test
    public void createUserViewModelTest() {
        // TODO: test createUserViewModel
    }

    /**
     * Test the property 'createts'
     */
    @Test
    public void createtsTest() {
        // TODO: test createts
    }

    /**
     * Test the property 'dueDate'
     */
    @Test
    public void dueDateTest() {
        // TODO: test dueDate
    }

    /**
     * Test the property 'dynaFormModel'
     */
    @Test
    public void dynaFormModelTest() {
        // TODO: test dynaFormModel
    }

    /**
     * Test the property 'dynaFormSectionAssignmentModel'
     */
    @Test
    public void dynaFormSectionAssignmentModelTest() {
        // TODO: test dynaFormSectionAssignmentModel
    }

    /**
     * Test the property 'formSummary'
     */
    @Test
    public void formSummaryTest() {
        // TODO: test formSummary
    }

    /**
     * Test the property 'graderUserModel'
     */
    @Test
    public void graderUserModelTest() {
        // TODO: test graderUserModel
    }

    /**
     * Test the property 'lastupdatets'
     */
    @Test
    public void lastupdatetsTest() {
        // TODO: test lastupdatets
    }

    /**
     * Test the property 'optedOutForEmail'
     */
    @Test
    public void optedOutForEmailTest() {
        // TODO: test optedOutForEmail
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'testEndts'
     */
    @Test
    public void testEndtsTest() {
        // TODO: test testEndts
    }

    /**
     * Test the property 'testResult'
     */
    @Test
    public void testResultTest() {
        // TODO: test testResult
    }

    /**
     * Test the property 'testStartts'
     */
    @Test
    public void testStarttsTest() {
        // TODO: test testStartts
    }

    /**
     * Test the property 'testTimeStatus'
     */
    @Test
    public void testTimeStatusTest() {
        // TODO: test testTimeStatus
    }

}
