/*
 * Expense Reports
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.sql.Timestamp;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EducationModel
 */
public class EducationModelTest {
    private final EducationModel model = new EducationModel();

    /**
     * Model tests for EducationModel
     */
    @Test
    public void testEducationModel() {
        // TODO: test EducationModel
    }

    /**
     * Test the property 'cid'
     */
    @Test
    public void cidTest() {
        // TODO: test cid
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'countryId'
     */
    @Test
    public void countryIdTest() {
        // TODO: test countryId
    }

    /**
     * Test the property 'course'
     */
    @Test
    public void courseTest() {
        // TODO: test course
    }

    /**
     * Test the property 'createts'
     */
    @Test
    public void createtsTest() {
        // TODO: test createts
    }

    /**
     * Test the property 'degree'
     */
    @Test
    public void degreeTest() {
        // TODO: test degree
    }

    /**
     * Test the property 'degreeId'
     */
    @Test
    public void degreeIdTest() {
        // TODO: test degreeId
    }

    /**
     * Test the property 'degreeType'
     */
    @Test
    public void degreeTypeTest() {
        // TODO: test degreeType
    }

    /**
     * Test the property 'educationId'
     */
    @Test
    public void educationIdTest() {
        // TODO: test educationId
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'expirationDate'
     */
    @Test
    public void expirationDateTest() {
        // TODO: test expirationDate
    }

    /**
     * Test the property 'gpa'
     */
    @Test
    public void gpaTest() {
        // TODO: test gpa
    }

    /**
     * Test the property 'graduation'
     */
    @Test
    public void graduationTest() {
        // TODO: test graduation
    }

    /**
     * Test the property 'institution'
     */
    @Test
    public void institutionTest() {
        // TODO: test institution
    }

    /**
     * Test the property 'institutionId'
     */
    @Test
    public void institutionIdTest() {
        // TODO: test institutionId
    }

    /**
     * Test the property 'isHighest'
     */
    @Test
    public void isHighestTest() {
        // TODO: test isHighest
    }

    /**
     * Test the property 'profileid'
     */
    @Test
    public void profileidTest() {
        // TODO: test profileid
    }

    /**
     * Test the property 'recruitid'
     */
    @Test
    public void recruitidTest() {
        // TODO: test recruitid
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

}
