/*
 * Expense Reports
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.GoalsGetGoalResponseReviewerUserModelLocationModelAddressModelListInnerCountryModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GoalsGetGoalResponseReviewerUserModelLocationModelAddressModelListInner
 */
public class GoalsGetGoalResponseReviewerUserModelLocationModelAddressModelListInnerTest {
    private final GoalsGetGoalResponseReviewerUserModelLocationModelAddressModelListInner model = new GoalsGetGoalResponseReviewerUserModelLocationModelAddressModelListInner();

    /**
     * Model tests for GoalsGetGoalResponseReviewerUserModelLocationModelAddressModelListInner
     */
    @Test
    public void testGoalsGetGoalResponseReviewerUserModelLocationModelAddressModelListInner() {
        // TODO: test GoalsGetGoalResponseReviewerUserModelLocationModelAddressModelListInner
    }

    /**
     * Test the property 'addressId'
     */
    @Test
    public void addressIdTest() {
        // TODO: test addressId
    }

    /**
     * Test the property 'addressLine1'
     */
    @Test
    public void addressLine1Test() {
        // TODO: test addressLine1
    }

    /**
     * Test the property 'addressLine2'
     */
    @Test
    public void addressLine2Test() {
        // TODO: test addressLine2
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'currentStatus'
     */
    @Test
    public void currentStatusTest() {
        // TODO: test currentStatus
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'zipCode'
     */
    @Test
    public void zipCodeTest() {
        // TODO: test zipCode
    }

    /**
     * Test the property 'createts'
     */
    @Test
    public void createtsTest() {
        // TODO: test createts
    }

    /**
     * Test the property 'cid'
     */
    @Test
    public void cidTest() {
        // TODO: test cid
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'candidateId'
     */
    @Test
    public void candidateIdTest() {
        // TODO: test candidateId
    }

    /**
     * Test the property 'addressType'
     */
    @Test
    public void addressTypeTest() {
        // TODO: test addressType
    }

    /**
     * Test the property 'locationId'
     */
    @Test
    public void locationIdTest() {
        // TODO: test locationId
    }

    /**
     * Test the property 'contactId'
     */
    @Test
    public void contactIdTest() {
        // TODO: test contactId
    }

    /**
     * Test the property 'countryId'
     */
    @Test
    public void countryIdTest() {
        // TODO: test countryId
    }

    /**
     * Test the property 'countryModel'
     */
    @Test
    public void countryModelTest() {
        // TODO: test countryModel
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'verificationStatus'
     */
    @Test
    public void verificationStatusTest() {
        // TODO: test verificationStatus
    }

    /**
     * Test the property 'custId'
     */
    @Test
    public void custIdTest() {
        // TODO: test custId
    }

    /**
     * Test the property 'mapUrl'
     */
    @Test
    public void mapUrlTest() {
        // TODO: test mapUrl
    }

    /**
     * Test the property 'createUserId'
     */
    @Test
    public void createUserIdTest() {
        // TODO: test createUserId
    }

    /**
     * Test the property 'extAppUID'
     */
    @Test
    public void extAppUIDTest() {
        // TODO: test extAppUID
    }

    /**
     * Test the property 'countryid'
     */
    @Test
    public void countryidTest() {
        // TODO: test countryid
    }

}
