/*
 * Expense Reports
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PtoPolicyModel;
import com.konfigthis.client.model.UserModel;
import com.konfigthis.client.model.UserViewModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for LeaveModel
 */
public class LeaveModelTest {
    private final LeaveModel model = new LeaveModel();

    /**
     * Model tests for LeaveModel
     */
    @Test
    public void testLeaveModel() {
        // TODO: test LeaveModel
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'createUserViewModel'
     */
    @Test
    public void createUserViewModelTest() {
        // TODO: test createUserViewModel
    }

    /**
     * Test the property 'date'
     */
    @Test
    public void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'endDateMeridiem'
     */
    @Test
    public void endDateMeridiemTest() {
        // TODO: test endDateMeridiem
    }

    /**
     * Test the property 'meridiem'
     */
    @Test
    public void meridiemTest() {
        // TODO: test meridiem
    }

    /**
     * Test the property 'numberOfDays'
     */
    @Test
    public void numberOfDaysTest() {
        // TODO: test numberOfDays
    }

    /**
     * Test the property 'ptoPolicyModel'
     */
    @Test
    public void ptoPolicyModelTest() {
        // TODO: test ptoPolicyModel
    }

    /**
     * Test the property 'totalLeaveDays'
     */
    @Test
    public void totalLeaveDaysTest() {
        // TODO: test totalLeaveDays
    }

    /**
     * Test the property 'totalLeaveHours'
     */
    @Test
    public void totalLeaveHoursTest() {
        // TODO: test totalLeaveHours
    }

    /**
     * Test the property 'userModel'
     */
    @Test
    public void userModelTest() {
        // TODO: test userModel
    }

}
