/*
 * Expense Reports
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PeopleAndPermissionsCreateOrUpdateUserDetailsRequestFinancialListInner
 */
public class PeopleAndPermissionsCreateOrUpdateUserDetailsRequestFinancialListInnerTest {
    private final PeopleAndPermissionsCreateOrUpdateUserDetailsRequestFinancialListInner model = new PeopleAndPermissionsCreateOrUpdateUserDetailsRequestFinancialListInner();

    /**
     * Model tests for PeopleAndPermissionsCreateOrUpdateUserDetailsRequestFinancialListInner
     */
    @Test
    public void testPeopleAndPermissionsCreateOrUpdateUserDetailsRequestFinancialListInner() {
        // TODO: test PeopleAndPermissionsCreateOrUpdateUserDetailsRequestFinancialListInner
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'period'
     */
    @Test
    public void periodTest() {
        // TODO: test period
    }

    /**
     * Test the property 'financialType'
     */
    @Test
    public void financialTypeTest() {
        // TODO: test financialType
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    public void currencyCodeTest() {
        // TODO: test currencyCode
    }

    /**
     * Test the property 'effectivedate'
     */
    @Test
    public void effectivedateTest() {
        // TODO: test effectivedate
    }

    /**
     * Test the property 'compensationType'
     */
    @Test
    public void compensationTypeTest() {
        // TODO: test compensationType
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'changeTypeId'
     */
    @Test
    public void changeTypeIdTest() {
        // TODO: test changeTypeId
    }

    /**
     * Test the property 'changeTypeCode'
     */
    @Test
    public void changeTypeCodeTest() {
        // TODO: test changeTypeCode
    }

    /**
     * Test the property 'extAppUID'
     */
    @Test
    public void extAppUIDTest() {
        // TODO: test extAppUID
    }

}
