/*
 * Expense Reports
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PeopleAndPermissionsCreateOrUpdateUserDetailsRequestAddressListInner;
import com.konfigthis.client.model.PeopleAndPermissionsCreateOrUpdateUserDetailsRequestContactListInner;
import com.konfigthis.client.model.PeopleAndPermissionsCreateOrUpdateUserDetailsRequestEducationListInner;
import com.konfigthis.client.model.PeopleAndPermissionsCreateOrUpdateUserDetailsRequestFinancialListInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
 */
public class PeopleAndPermissionsCreateOrUpdateUserDetailsRequestTest {
    private final PeopleAndPermissionsCreateOrUpdateUserDetailsRequest model = new PeopleAndPermissionsCreateOrUpdateUserDetailsRequest();

    /**
     * Model tests for PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
     */
    @Test
    public void testPeopleAndPermissionsCreateOrUpdateUserDetailsRequest() {
        // TODO: test PeopleAndPermissionsCreateOrUpdateUserDetailsRequest
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'empId'
     */
    @Test
    public void empIdTest() {
        // TODO: test empId
    }

    /**
     * Test the property 'gender'
     */
    @Test
    public void genderTest() {
        // TODO: test gender
    }

    /**
     * Test the property 'guid'
     */
    @Test
    public void guidTest() {
        // TODO: test guid
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'displayFullName'
     */
    @Test
    public void displayFullNameTest() {
        // TODO: test displayFullName
    }

    /**
     * Test the property 'middleName'
     */
    @Test
    public void middleNameTest() {
        // TODO: test middleName
    }

    /**
     * Test the property 'secondLastName'
     */
    @Test
    public void secondLastNameTest() {
        // TODO: test secondLastName
    }

    /**
     * Test the property 'shortName'
     */
    @Test
    public void shortNameTest() {
        // TODO: test shortName
    }

    /**
     * Test the property 'namePronunciation'
     */
    @Test
    public void namePronunciationTest() {
        // TODO: test namePronunciation
    }

    /**
     * Test the property 'familySuffix'
     */
    @Test
    public void familySuffixTest() {
        // TODO: test familySuffix
    }

    /**
     * Test the property 'workerType'
     */
    @Test
    public void workerTypeTest() {
        // TODO: test workerType
    }

    /**
     * Test the property 'userDateOfBirth'
     */
    @Test
    public void userDateOfBirthTest() {
        // TODO: test userDateOfBirth
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'cellPhone'
     */
    @Test
    public void cellPhoneTest() {
        // TODO: test cellPhone
    }

    /**
     * Test the property 'position'
     */
    @Test
    public void positionTest() {
        // TODO: test position
    }

    /**
     * Test the property 'departmentID'
     */
    @Test
    public void departmentIDTest() {
        // TODO: test departmentID
    }

    /**
     * Test the property 'locationId'
     */
    @Test
    public void locationIdTest() {
        // TODO: test locationId
    }

    /**
     * Test the property 'locationName'
     */
    @Test
    public void locationNameTest() {
        // TODO: test locationName
    }

    /**
     * Test the property 'userStartDate'
     */
    @Test
    public void userStartDateTest() {
        // TODO: test userStartDate
    }

    /**
     * Test the property 'reportsToEmail'
     */
    @Test
    public void reportsToEmailTest() {
        // TODO: test reportsToEmail
    }

    /**
     * Test the property 'addressList'
     */
    @Test
    public void addressListTest() {
        // TODO: test addressList
    }

    /**
     * Test the property 'educationList'
     */
    @Test
    public void educationListTest() {
        // TODO: test educationList
    }

    /**
     * Test the property 'contactList'
     */
    @Test
    public void contactListTest() {
        // TODO: test contactList
    }

    /**
     * Test the property 'financialList'
     */
    @Test
    public void financialListTest() {
        // TODO: test financialList
    }

    /**
     * Test the property 'customFieldValues'
     */
    @Test
    public void customFieldValuesTest() {
        // TODO: test customFieldValues
    }

}
