/*
 * Expense Reports
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PeopleAndPermissionsGetUsersResponseDataInnerUserReporterList;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PeopleAndPermissionsGetUsersResponseDataInner
 */
public class PeopleAndPermissionsGetUsersResponseDataInnerTest {
    private final PeopleAndPermissionsGetUsersResponseDataInner model = new PeopleAndPermissionsGetUsersResponseDataInner();

    /**
     * Model tests for PeopleAndPermissionsGetUsersResponseDataInner
     */
    @Test
    public void testPeopleAndPermissionsGetUsersResponseDataInner() {
        // TODO: test PeopleAndPermissionsGetUsersResponseDataInner
    }

    /**
     * Test the property 'resourceId'
     */
    @Test
    public void resourceIdTest() {
        // TODO: test resourceId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'position'
     */
    @Test
    public void positionTest() {
        // TODO: test position
    }

    /**
     * Test the property 'assignments'
     */
    @Test
    public void assignmentsTest() {
        // TODO: test assignments
    }

    /**
     * Test the property 'allocation'
     */
    @Test
    public void allocationTest() {
        // TODO: test allocation
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'workerType'
     */
    @Test
    public void workerTypeTest() {
        // TODO: test workerType
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'timeZone'
     */
    @Test
    public void timeZoneTest() {
        // TODO: test timeZone
    }

    /**
     * Test the property 'notes'
     */
    @Test
    public void notesTest() {
        // TODO: test notes
    }

    /**
     * Test the property 'emailAddress'
     */
    @Test
    public void emailAddressTest() {
        // TODO: test emailAddress
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'im'
     */
    @Test
    public void imTest() {
        // TODO: test im
    }

    /**
     * Test the property 'dateOfBirth'
     */
    @Test
    public void dateOfBirthTest() {
        // TODO: test dateOfBirth
    }

    /**
     * Test the property 'gender'
     */
    @Test
    public void genderTest() {
        // TODO: test gender
    }

    /**
     * Test the property 'imageName'
     */
    @Test
    public void imageNameTest() {
        // TODO: test imageName
    }

    /**
     * Test the property 'customFieldList'
     */
    @Test
    public void customFieldListTest() {
        // TODO: test customFieldList
    }

    /**
     * Test the property 'department'
     */
    @Test
    public void departmentTest() {
        // TODO: test department
    }

    /**
     * Test the property 'departmentLabel'
     */
    @Test
    public void departmentLabelTest() {
        // TODO: test departmentLabel
    }

    /**
     * Test the property 'profileName'
     */
    @Test
    public void profileNameTest() {
        // TODO: test profileName
    }

    /**
     * Test the property 'userReporterList'
     */
    @Test
    public void userReporterListTest() {
        // TODO: test userReporterList
    }

    /**
     * Test the property 'empId'
     */
    @Test
    public void empIdTest() {
        // TODO: test empId
    }

}
