/*
 * Expense Reports
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProjectGroupModel
 */
public class ProjectGroupModelTest {
    private final ProjectGroupModel model = new ProjectGroupModel();

    /**
     * Model tests for ProjectGroupModel
     */
    @Test
    public void testProjectGroupModel() {
        // TODO: test ProjectGroupModel
    }

    /**
     * Test the property 'cid'
     */
    @Test
    public void cidTest() {
        // TODO: test cid
    }

    /**
     * Test the property 'groupDesc'
     */
    @Test
    public void groupDescTest() {
        // TODO: test groupDesc
    }

    /**
     * Test the property 'groupName'
     */
    @Test
    public void groupNameTest() {
        // TODO: test groupName
    }

    /**
     * Test the property 'pgroupid'
     */
    @Test
    public void pgroupidTest() {
        // TODO: test pgroupid
    }

}
