/*
 * Expense Reports
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AppraisalModel;
import com.konfigthis.client.model.AttachmentModel;
import com.konfigthis.client.model.CandidateModel;
import com.konfigthis.client.model.DynamicFormAssignmentModel;
import com.konfigthis.client.model.UserGroupModel;
import com.konfigthis.client.model.UserModel;
import com.konfigthis.client.model.UserTrainingModel;
import com.konfigthis.client.model.UserWorkflowModel;
import com.konfigthis.client.model.WorkflowParameterAssignmentModel;
import com.konfigthis.client.model.WorkflowStepModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.sql.Timestamp;
import java.time.LocalDate;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TaskModel
 */
public class TaskModelTest {
    private final TaskModel model = new TaskModel();

    /**
     * Model tests for TaskModel
     */
    @Test
    public void testTaskModel() {
        // TODO: test TaskModel
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'appraisalId'
     */
    @Test
    public void appraisalIdTest() {
        // TODO: test appraisalId
    }

    /**
     * Test the property 'assgnCandModel'
     */
    @Test
    public void assgnCandModelTest() {
        // TODO: test assgnCandModel
    }

    /**
     * Test the property 'assgnUserModel'
     */
    @Test
    public void assgnUserModelTest() {
        // TODO: test assgnUserModel
    }

    /**
     * Test the property 'assignedUserId'
     */
    @Test
    public void assignedUserIdTest() {
        // TODO: test assignedUserId
    }

    /**
     * Test the property 'ci'
     */
    @Test
    public void ciTest() {
        // TODO: test ci
    }

    /**
     * Test the property 'createUserId'
     */
    @Test
    public void createUserIdTest() {
        // TODO: test createUserId
    }

    /**
     * Test the property 'createts'
     */
    @Test
    public void createtsTest() {
        // TODO: test createts
    }

    /**
     * Test the property 'dueDate'
     */
    @Test
    public void dueDateTest() {
        // TODO: test dueDate
    }

    /**
     * Test the property 'lastEdit'
     */
    @Test
    public void lastEditTest() {
        // TODO: test lastEdit
    }

    /**
     * Test the property 'launchts'
     */
    @Test
    public void launchtsTest() {
        // TODO: test launchts
    }

    /**
     * Test the property 'phasename'
     */
    @Test
    public void phasenameTest() {
        // TODO: test phasename
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    public void projectIdTest() {
        // TODO: test projectId
    }

    /**
     * Test the property 'recruitId'
     */
    @Test
    public void recruitIdTest() {
        // TODO: test recruitId
    }

    /**
     * Test the property 'relatedDynamicFormAssignmentModel'
     */
    @Test
    public void relatedDynamicFormAssignmentModelTest() {
        // TODO: test relatedDynamicFormAssignmentModel
    }

    /**
     * Test the property 'releventAppraisalModel'
     */
    @Test
    public void releventAppraisalModelTest() {
        // TODO: test releventAppraisalModel
    }

    /**
     * Test the property 'releventAttachmentModel'
     */
    @Test
    public void releventAttachmentModelTest() {
        // TODO: test releventAttachmentModel
    }

    /**
     * Test the property 'releventUserTrainingModel'
     */
    @Test
    public void releventUserTrainingModelTest() {
        // TODO: test releventUserTrainingModel
    }

    /**
     * Test the property 'statusCode'
     */
    @Test
    public void statusCodeTest() {
        // TODO: test statusCode
    }

    /**
     * Test the property 'systemTask'
     */
    @Test
    public void systemTaskTest() {
        // TODO: test systemTask
    }

    /**
     * Test the property 'taskId'
     */
    @Test
    public void taskIdTest() {
        // TODO: test taskId
    }

    /**
     * Test the property 'taskUID'
     */
    @Test
    public void taskUIDTest() {
        // TODO: test taskUID
    }

    /**
     * Test the property 'transitionName'
     */
    @Test
    public void transitionNameTest() {
        // TODO: test transitionName
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'userGroupModel'
     */
    @Test
    public void userGroupModelTest() {
        // TODO: test userGroupModel
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'userModel'
     */
    @Test
    public void userModelTest() {
        // TODO: test userModel
    }

    /**
     * Test the property 'userWorkflowModel'
     */
    @Test
    public void userWorkflowModelTest() {
        // TODO: test userWorkflowModel
    }

    /**
     * Test the property 'workflowParameterAssignmentModel'
     */
    @Test
    public void workflowParameterAssignmentModelTest() {
        // TODO: test workflowParameterAssignmentModel
    }

    /**
     * Test the property 'workflowStepId'
     */
    @Test
    public void workflowStepIdTest() {
        // TODO: test workflowStepId
    }

    /**
     * Test the property 'workflowStepModel'
     */
    @Test
    public void workflowStepModelTest() {
        // TODO: test workflowStepModel
    }

}
