/*
 * Expense Reports
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WorkerTypeModel
 */
public class WorkerTypeModelTest {
    private final WorkerTypeModel model = new WorkerTypeModel();

    /**
     * Model tests for WorkerTypeModel
     */
    @Test
    public void testWorkerTypeModel() {
        // TODO: test WorkerTypeModel
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'cid'
     */
    @Test
    public void cidTest() {
        // TODO: test cid
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'createuserid'
     */
    @Test
    public void createuseridTest() {
        // TODO: test createuserid
    }

    /**
     * Test the property 'wtid'
     */
    @Test
    public void wtidTest() {
        // TODO: test wtid
    }

}
