/*
 * Expense Reports
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DynamicFormAssignmentModel;
import com.konfigthis.client.model.DynamicFormSectionModel;
import com.konfigthis.client.model.UserGroupModel;
import com.konfigthis.client.model.UserViewModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.sql.Timestamp;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * DynaFormSectionAssignmentModel
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class DynaFormSectionAssignmentModel {
  public static final String SERIALIZED_NAME_ASSIGNEE_ROLE = "assigneeRole";
  @SerializedName(SERIALIZED_NAME_ASSIGNEE_ROLE)
  private String assigneeRole;

  public static final String SERIALIZED_NAME_CID = "cid";
  @SerializedName(SERIALIZED_NAME_CID)
  private Integer cid;

  public static final String SERIALIZED_NAME_COMPLETED_BY = "completedBy";
  @SerializedName(SERIALIZED_NAME_COMPLETED_BY)
  private UserViewModel completedBy;

  public static final String SERIALIZED_NAME_CREATETS = "createts";
  @SerializedName(SERIALIZED_NAME_CREATETS)
  private Timestamp createts;

  public static final String SERIALIZED_NAME_DYNA_FORM_SECTION_ASSIGN_ID = "dynaFormSectionAssignId";
  @SerializedName(SERIALIZED_NAME_DYNA_FORM_SECTION_ASSIGN_ID)
  private Integer dynaFormSectionAssignId;

  public static final String SERIALIZED_NAME_DYNAMIC_FORM_ASSIGNMENT_MODEL = "dynamicFormAssignmentModel";
  @SerializedName(SERIALIZED_NAME_DYNAMIC_FORM_ASSIGNMENT_MODEL)
  private DynamicFormAssignmentModel dynamicFormAssignmentModel;

  public static final String SERIALIZED_NAME_DYNAMIC_FORM_SECTION_MODEL = "dynamicFormSectionModel";
  @SerializedName(SERIALIZED_NAME_DYNAMIC_FORM_SECTION_MODEL)
  private DynamicFormSectionModel dynamicFormSectionModel;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_USER_GROUP_MODEL = "userGroupModel";
  @SerializedName(SERIALIZED_NAME_USER_GROUP_MODEL)
  private UserGroupModel userGroupModel;

  public static final String SERIALIZED_NAME_USER_VIEW_MODEL = "userViewModel";
  @SerializedName(SERIALIZED_NAME_USER_VIEW_MODEL)
  private UserViewModel userViewModel;

  public DynaFormSectionAssignmentModel() {
  }

  public DynaFormSectionAssignmentModel assigneeRole(String assigneeRole) {
    
    
    
    
    this.assigneeRole = assigneeRole;
    return this;
  }

   /**
   * Get assigneeRole
   * @return assigneeRole
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAssigneeRole() {
    return assigneeRole;
  }


  public void setAssigneeRole(String assigneeRole) {
    
    
    
    this.assigneeRole = assigneeRole;
  }


  public DynaFormSectionAssignmentModel cid(Integer cid) {
    
    
    
    
    this.cid = cid;
    return this;
  }

   /**
   * Get cid
   * @return cid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getCid() {
    return cid;
  }


  public void setCid(Integer cid) {
    
    
    
    this.cid = cid;
  }


  public DynaFormSectionAssignmentModel completedBy(UserViewModel completedBy) {
    
    
    
    
    this.completedBy = completedBy;
    return this;
  }

   /**
   * Get completedBy
   * @return completedBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UserViewModel getCompletedBy() {
    return completedBy;
  }


  public void setCompletedBy(UserViewModel completedBy) {
    
    
    
    this.completedBy = completedBy;
  }


  public DynaFormSectionAssignmentModel createts(Timestamp createts) {
    
    
    
    
    this.createts = createts;
    return this;
  }

   /**
   * Get createts
   * @return createts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Timestamp getCreatets() {
    return createts;
  }


  public void setCreatets(Timestamp createts) {
    
    
    
    this.createts = createts;
  }


  public DynaFormSectionAssignmentModel dynaFormSectionAssignId(Integer dynaFormSectionAssignId) {
    
    
    
    
    this.dynaFormSectionAssignId = dynaFormSectionAssignId;
    return this;
  }

   /**
   * Get dynaFormSectionAssignId
   * @return dynaFormSectionAssignId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getDynaFormSectionAssignId() {
    return dynaFormSectionAssignId;
  }


  public void setDynaFormSectionAssignId(Integer dynaFormSectionAssignId) {
    
    
    
    this.dynaFormSectionAssignId = dynaFormSectionAssignId;
  }


  public DynaFormSectionAssignmentModel dynamicFormAssignmentModel(DynamicFormAssignmentModel dynamicFormAssignmentModel) {
    
    
    
    
    this.dynamicFormAssignmentModel = dynamicFormAssignmentModel;
    return this;
  }

   /**
   * Get dynamicFormAssignmentModel
   * @return dynamicFormAssignmentModel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DynamicFormAssignmentModel getDynamicFormAssignmentModel() {
    return dynamicFormAssignmentModel;
  }


  public void setDynamicFormAssignmentModel(DynamicFormAssignmentModel dynamicFormAssignmentModel) {
    
    
    
    this.dynamicFormAssignmentModel = dynamicFormAssignmentModel;
  }


  public DynaFormSectionAssignmentModel dynamicFormSectionModel(DynamicFormSectionModel dynamicFormSectionModel) {
    
    
    
    
    this.dynamicFormSectionModel = dynamicFormSectionModel;
    return this;
  }

   /**
   * Get dynamicFormSectionModel
   * @return dynamicFormSectionModel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DynamicFormSectionModel getDynamicFormSectionModel() {
    return dynamicFormSectionModel;
  }


  public void setDynamicFormSectionModel(DynamicFormSectionModel dynamicFormSectionModel) {
    
    
    
    this.dynamicFormSectionModel = dynamicFormSectionModel;
  }


  public DynaFormSectionAssignmentModel status(String status) {
    
    
    
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    
    
    
    this.status = status;
  }


  public DynaFormSectionAssignmentModel userGroupModel(UserGroupModel userGroupModel) {
    
    
    
    
    this.userGroupModel = userGroupModel;
    return this;
  }

   /**
   * Get userGroupModel
   * @return userGroupModel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UserGroupModel getUserGroupModel() {
    return userGroupModel;
  }


  public void setUserGroupModel(UserGroupModel userGroupModel) {
    
    
    
    this.userGroupModel = userGroupModel;
  }


  public DynaFormSectionAssignmentModel userViewModel(UserViewModel userViewModel) {
    
    
    
    
    this.userViewModel = userViewModel;
    return this;
  }

   /**
   * Get userViewModel
   * @return userViewModel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UserViewModel getUserViewModel() {
    return userViewModel;
  }


  public void setUserViewModel(UserViewModel userViewModel) {
    
    
    
    this.userViewModel = userViewModel;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the DynaFormSectionAssignmentModel instance itself
   */
  public DynaFormSectionAssignmentModel putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DynaFormSectionAssignmentModel dynaFormSectionAssignmentModel = (DynaFormSectionAssignmentModel) o;
    return Objects.equals(this.assigneeRole, dynaFormSectionAssignmentModel.assigneeRole) &&
        Objects.equals(this.cid, dynaFormSectionAssignmentModel.cid) &&
        Objects.equals(this.completedBy, dynaFormSectionAssignmentModel.completedBy) &&
        Objects.equals(this.createts, dynaFormSectionAssignmentModel.createts) &&
        Objects.equals(this.dynaFormSectionAssignId, dynaFormSectionAssignmentModel.dynaFormSectionAssignId) &&
        Objects.equals(this.dynamicFormAssignmentModel, dynaFormSectionAssignmentModel.dynamicFormAssignmentModel) &&
        Objects.equals(this.dynamicFormSectionModel, dynaFormSectionAssignmentModel.dynamicFormSectionModel) &&
        Objects.equals(this.status, dynaFormSectionAssignmentModel.status) &&
        Objects.equals(this.userGroupModel, dynaFormSectionAssignmentModel.userGroupModel) &&
        Objects.equals(this.userViewModel, dynaFormSectionAssignmentModel.userViewModel)&&
        Objects.equals(this.additionalProperties, dynaFormSectionAssignmentModel.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assigneeRole, cid, completedBy, createts, dynaFormSectionAssignId, dynamicFormAssignmentModel, dynamicFormSectionModel, status, userGroupModel, userViewModel, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DynaFormSectionAssignmentModel {\n");
    sb.append("    assigneeRole: ").append(toIndentedString(assigneeRole)).append("\n");
    sb.append("    cid: ").append(toIndentedString(cid)).append("\n");
    sb.append("    completedBy: ").append(toIndentedString(completedBy)).append("\n");
    sb.append("    createts: ").append(toIndentedString(createts)).append("\n");
    sb.append("    dynaFormSectionAssignId: ").append(toIndentedString(dynaFormSectionAssignId)).append("\n");
    sb.append("    dynamicFormAssignmentModel: ").append(toIndentedString(dynamicFormAssignmentModel)).append("\n");
    sb.append("    dynamicFormSectionModel: ").append(toIndentedString(dynamicFormSectionModel)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    userGroupModel: ").append(toIndentedString(userGroupModel)).append("\n");
    sb.append("    userViewModel: ").append(toIndentedString(userViewModel)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("assigneeRole");
    openapiFields.add("cid");
    openapiFields.add("completedBy");
    openapiFields.add("createts");
    openapiFields.add("dynaFormSectionAssignId");
    openapiFields.add("dynamicFormAssignmentModel");
    openapiFields.add("dynamicFormSectionModel");
    openapiFields.add("status");
    openapiFields.add("userGroupModel");
    openapiFields.add("userViewModel");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to DynaFormSectionAssignmentModel
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!DynaFormSectionAssignmentModel.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DynaFormSectionAssignmentModel is not found in the empty JSON string", DynaFormSectionAssignmentModel.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("assigneeRole") != null && !jsonObj.get("assigneeRole").isJsonNull()) && !jsonObj.get("assigneeRole").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `assigneeRole` to be a primitive type in the JSON string but got `%s`", jsonObj.get("assigneeRole").toString()));
      }
      // validate the optional field `completedBy`
      if (jsonObj.get("completedBy") != null && !jsonObj.get("completedBy").isJsonNull()) {
        UserViewModel.validateJsonObject(jsonObj.getAsJsonObject("completedBy"));
      }
      // validate the optional field `createts`
      if (jsonObj.get("createts") != null && !jsonObj.get("createts").isJsonNull()) {
        Timestamp.validateJsonObject(jsonObj.getAsJsonObject("createts"));
      }
      // validate the optional field `dynamicFormAssignmentModel`
      if (jsonObj.get("dynamicFormAssignmentModel") != null && !jsonObj.get("dynamicFormAssignmentModel").isJsonNull()) {
        DynamicFormAssignmentModel.validateJsonObject(jsonObj.getAsJsonObject("dynamicFormAssignmentModel"));
      }
      // validate the optional field `dynamicFormSectionModel`
      if (jsonObj.get("dynamicFormSectionModel") != null && !jsonObj.get("dynamicFormSectionModel").isJsonNull()) {
        DynamicFormSectionModel.validateJsonObject(jsonObj.getAsJsonObject("dynamicFormSectionModel"));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      // validate the optional field `userGroupModel`
      if (jsonObj.get("userGroupModel") != null && !jsonObj.get("userGroupModel").isJsonNull()) {
        UserGroupModel.validateJsonObject(jsonObj.getAsJsonObject("userGroupModel"));
      }
      // validate the optional field `userViewModel`
      if (jsonObj.get("userViewModel") != null && !jsonObj.get("userViewModel").isJsonNull()) {
        UserViewModel.validateJsonObject(jsonObj.getAsJsonObject("userViewModel"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DynaFormSectionAssignmentModel.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DynaFormSectionAssignmentModel' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DynaFormSectionAssignmentModel> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DynaFormSectionAssignmentModel.class));

       return (TypeAdapter<T>) new TypeAdapter<DynaFormSectionAssignmentModel>() {
           @Override
           public void write(JsonWriter out, DynaFormSectionAssignmentModel value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public DynaFormSectionAssignmentModel read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             DynaFormSectionAssignmentModel instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DynaFormSectionAssignmentModel given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DynaFormSectionAssignmentModel
  * @throws IOException if the JSON string is invalid with respect to DynaFormSectionAssignmentModel
  */
  public static DynaFormSectionAssignmentModel fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DynaFormSectionAssignmentModel.class);
  }

 /**
  * Convert an instance of DynaFormSectionAssignmentModel to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

