/*
 * Expense Reports
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.GoalsGetGoalResponseAssignedUserModel;
import com.konfigthis.client.model.GoalsGetGoalResponseGoalCollaborationModelInner;
import com.konfigthis.client.model.GoalsGetGoalResponseGoalTypeModel;
import com.konfigthis.client.model.GoalsGetGoalResponseProjectModel;
import com.konfigthis.client.model.GoalsGetGoalResponseReviewerUserModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * GoalsGetGoalResponse
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class GoalsGetGoalResponse {
  public static final String SERIALIZED_NAME_SUMMARY = "summary";
  @SerializedName(SERIALIZED_NAME_SUMMARY)
  private String summary;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_GOAL_ID = "goalId";
  @SerializedName(SERIALIZED_NAME_GOAL_ID)
  private String goalId;

  public static final String SERIALIZED_NAME_ADDITIVE = "additive";
  @SerializedName(SERIALIZED_NAME_ADDITIVE)
  private String additive;

  public static final String SERIALIZED_NAME_VISIBLE_TO_DIRECT_REPORTS = "visibleToDirectReports";
  @SerializedName(SERIALIZED_NAME_VISIBLE_TO_DIRECT_REPORTS)
  private String visibleToDirectReports;

  public static final String SERIALIZED_NAME_FREEZE_GOAL = "freezeGoal";
  @SerializedName(SERIALIZED_NAME_FREEZE_GOAL)
  private String freezeGoal;

  public static final String SERIALIZED_NAME_IS_FORWARD = "isForward";
  @SerializedName(SERIALIZED_NAME_IS_FORWARD)
  private String isForward;

  public static final String SERIALIZED_NAME_COMPANY_GOAL = "companyGoal";
  @SerializedName(SERIALIZED_NAME_COMPANY_GOAL)
  private String companyGoal;

  public static final String SERIALIZED_NAME_ELAPSED_TIME_RATIO = "elapsedTimeRatio";
  @SerializedName(SERIALIZED_NAME_ELAPSED_TIME_RATIO)
  private String elapsedTimeRatio;

  public static final String SERIALIZED_NAME_COMPLETION_RATIO = "completionRatio";
  @SerializedName(SERIALIZED_NAME_COMPLETION_RATIO)
  private String completionRatio;

  public static final String SERIALIZED_NAME_PROGRESS_RATIO = "progressRatio";
  @SerializedName(SERIALIZED_NAME_PROGRESS_RATIO)
  private String progressRatio;

  public static final String SERIALIZED_NAME_TYPECODE = "typecode";
  @SerializedName(SERIALIZED_NAME_TYPECODE)
  private String typecode;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  private String state;

  public static final String SERIALIZED_NAME_PREDICTIVE_INDEX = "predictiveIndex";
  @SerializedName(SERIALIZED_NAME_PREDICTIVE_INDEX)
  private String predictiveIndex;

  public static final String SERIALIZED_NAME_OBJECTIVE_ID = "objectiveId";
  @SerializedName(SERIALIZED_NAME_OBJECTIVE_ID)
  private String objectiveId;

  public static final String SERIALIZED_NAME_CID = "cid";
  @SerializedName(SERIALIZED_NAME_CID)
  private String cid;

  public static final String SERIALIZED_NAME_DISPOSITION = "disposition";
  @SerializedName(SERIALIZED_NAME_DISPOSITION)
  private String disposition;

  public static final String SERIALIZED_NAME_UNITS = "units";
  @SerializedName(SERIALIZED_NAME_UNITS)
  private String units;

  public static final String SERIALIZED_NAME_ASSIGNED_USER_MODEL = "assignedUserModel";
  @SerializedName(SERIALIZED_NAME_ASSIGNED_USER_MODEL)
  private GoalsGetGoalResponseAssignedUserModel assignedUserModel;

  public static final String SERIALIZED_NAME_REVIEWER_USER_MODEL = "reviewerUserModel";
  @SerializedName(SERIALIZED_NAME_REVIEWER_USER_MODEL)
  private GoalsGetGoalResponseReviewerUserModel reviewerUserModel;

  public static final String SERIALIZED_NAME_GOAL_COLLABORATION_MODEL = "goalCollaborationModel";
  @SerializedName(SERIALIZED_NAME_GOAL_COLLABORATION_MODEL)
  private List<GoalsGetGoalResponseGoalCollaborationModelInner> goalCollaborationModel = null;

  public static final String SERIALIZED_NAME_CREDITEATETS = "crediteatets";
  @SerializedName(SERIALIZED_NAME_CREDITEATETS)
  private String crediteatets;

  public static final String SERIALIZED_NAME_COMMENT_CREDITEATETS = "commentCrediteatets";
  @SerializedName(SERIALIZED_NAME_COMMENT_CREDITEATETS)
  private String commentCrediteatets;

  public static final String SERIALIZED_NAME_COMMENT_DESCRIPTION = "commentDescription";
  @SerializedName(SERIALIZED_NAME_COMMENT_DESCRIPTION)
  private String commentDescription;

  public static final String SERIALIZED_NAME_UNAME = "uname";
  @SerializedName(SERIALIZED_NAME_UNAME)
  private String uname;

  public static final String SERIALIZED_NAME_HAS_GOAL_APPROVAL_PERMISSION = "hasGoalApprovalPermission";
  @SerializedName(SERIALIZED_NAME_HAS_GOAL_APPROVAL_PERMISSION)
  private String hasGoalApprovalPermission;

  public static final String SERIALIZED_NAME_BEGINDATE = "begindate";
  @SerializedName(SERIALIZED_NAME_BEGINDATE)
  private String begindate;

  public static final String SERIALIZED_NAME_GOAL_WEIGHTAGE = "goalWeightage";
  @SerializedName(SERIALIZED_NAME_GOAL_WEIGHTAGE)
  private String goalWeightage;

  public static final String SERIALIZED_NAME_CREATEUSERID = "createuserid";
  @SerializedName(SERIALIZED_NAME_CREATEUSERID)
  private String createuserid;

  public static final String SERIALIZED_NAME_CREATETS = "createts";
  @SerializedName(SERIALIZED_NAME_CREATETS)
  private Integer createts = 0;

  public static final String SERIALIZED_NAME_PROJECT_MODEL = "projectModel";
  @SerializedName(SERIALIZED_NAME_PROJECT_MODEL)
  private GoalsGetGoalResponseProjectModel projectModel;

  public static final String SERIALIZED_NAME_GOAL_TYPE_MODEL = "goalTypeModel";
  @SerializedName(SERIALIZED_NAME_GOAL_TYPE_MODEL)
  private GoalsGetGoalResponseGoalTypeModel goalTypeModel;

  public static final String SERIALIZED_NAME_PARENT_GOAL_ID = "parentGoalId";
  @SerializedName(SERIALIZED_NAME_PARENT_GOAL_ID)
  private String parentGoalId;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_CREATE_USER_ID = "createUserId";
  @SerializedName(SERIALIZED_NAME_CREATE_USER_ID)
  private String createUserId;

  public static final String SERIALIZED_NAME_LAST_UPDATE_USER_ID = "lastUpdateUserId";
  @SerializedName(SERIALIZED_NAME_LAST_UPDATE_USER_ID)
  private String lastUpdateUserId;

  public static final String SERIALIZED_NAME_PROJECTID = "projectid";
  @SerializedName(SERIALIZED_NAME_PROJECTID)
  private String projectid;

  public static final String SERIALIZED_NAME_TARGETDATE = "targetdate";
  @SerializedName(SERIALIZED_NAME_TARGETDATE)
  private String targetdate;

  public static final String SERIALIZED_NAME_INITIALVALUE = "initialvalue";
  @SerializedName(SERIALIZED_NAME_INITIALVALUE)
  private String initialvalue;

  public static final String SERIALIZED_NAME_CURRENTVALUE = "currentvalue";
  @SerializedName(SERIALIZED_NAME_CURRENTVALUE)
  private String currentvalue;

  public static final String SERIALIZED_NAME_GOALVALUE = "goalvalue";
  @SerializedName(SERIALIZED_NAME_GOALVALUE)
  private String goalvalue;

  public GoalsGetGoalResponse() {
  }

  public GoalsGetGoalResponse summary(String summary) {
    
    
    
    
    this.summary = summary;
    return this;
  }

   /**
   * Get summary
   * @return summary
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "string", value = "")

  public String getSummary() {
    return summary;
  }


  public void setSummary(String summary) {
    
    
    
    this.summary = summary;
  }


  public GoalsGetGoalResponse description(String description) {
    
    
    
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "string", value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    
    
    
    this.description = description;
  }


  public GoalsGetGoalResponse goalId(String goalId) {
    
    
    
    
    this.goalId = goalId;
    return this;
  }

   /**
   * Get goalId
   * @return goalId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "int", value = "")

  public String getGoalId() {
    return goalId;
  }


  public void setGoalId(String goalId) {
    
    
    
    this.goalId = goalId;
  }


  public GoalsGetGoalResponse additive(String additive) {
    
    
    
    
    this.additive = additive;
    return this;
  }

   /**
   * Get additive
   * @return additive
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "int", value = "")

  public String getAdditive() {
    return additive;
  }


  public void setAdditive(String additive) {
    
    
    
    this.additive = additive;
  }


  public GoalsGetGoalResponse visibleToDirectReports(String visibleToDirectReports) {
    
    
    
    
    this.visibleToDirectReports = visibleToDirectReports;
    return this;
  }

   /**
   * Get visibleToDirectReports
   * @return visibleToDirectReports
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "int", value = "")

  public String getVisibleToDirectReports() {
    return visibleToDirectReports;
  }


  public void setVisibleToDirectReports(String visibleToDirectReports) {
    
    
    
    this.visibleToDirectReports = visibleToDirectReports;
  }


  public GoalsGetGoalResponse freezeGoal(String freezeGoal) {
    
    
    
    
    this.freezeGoal = freezeGoal;
    return this;
  }

   /**
   * Get freezeGoal
   * @return freezeGoal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "int", value = "")

  public String getFreezeGoal() {
    return freezeGoal;
  }


  public void setFreezeGoal(String freezeGoal) {
    
    
    
    this.freezeGoal = freezeGoal;
  }


  public GoalsGetGoalResponse isForward(String isForward) {
    
    
    
    
    this.isForward = isForward;
    return this;
  }

   /**
   * Get isForward
   * @return isForward
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "boolean", value = "")

  public String getIsForward() {
    return isForward;
  }


  public void setIsForward(String isForward) {
    
    
    
    this.isForward = isForward;
  }


  public GoalsGetGoalResponse companyGoal(String companyGoal) {
    
    
    
    
    this.companyGoal = companyGoal;
    return this;
  }

   /**
   * Get companyGoal
   * @return companyGoal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "int", value = "")

  public String getCompanyGoal() {
    return companyGoal;
  }


  public void setCompanyGoal(String companyGoal) {
    
    
    
    this.companyGoal = companyGoal;
  }


  public GoalsGetGoalResponse elapsedTimeRatio(String elapsedTimeRatio) {
    
    
    
    
    this.elapsedTimeRatio = elapsedTimeRatio;
    return this;
  }

   /**
   * Get elapsedTimeRatio
   * @return elapsedTimeRatio
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "float", value = "")

  public String getElapsedTimeRatio() {
    return elapsedTimeRatio;
  }


  public void setElapsedTimeRatio(String elapsedTimeRatio) {
    
    
    
    this.elapsedTimeRatio = elapsedTimeRatio;
  }


  public GoalsGetGoalResponse completionRatio(String completionRatio) {
    
    
    
    
    this.completionRatio = completionRatio;
    return this;
  }

   /**
   * Get completionRatio
   * @return completionRatio
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "float", value = "")

  public String getCompletionRatio() {
    return completionRatio;
  }


  public void setCompletionRatio(String completionRatio) {
    
    
    
    this.completionRatio = completionRatio;
  }


  public GoalsGetGoalResponse progressRatio(String progressRatio) {
    
    
    
    
    this.progressRatio = progressRatio;
    return this;
  }

   /**
   * Get progressRatio
   * @return progressRatio
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "float", value = "")

  public String getProgressRatio() {
    return progressRatio;
  }


  public void setProgressRatio(String progressRatio) {
    
    
    
    this.progressRatio = progressRatio;
  }


  public GoalsGetGoalResponse typecode(String typecode) {
    
    
    
    
    this.typecode = typecode;
    return this;
  }

   /**
   * Get typecode
   * @return typecode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "string", value = "")

  public String getTypecode() {
    return typecode;
  }


  public void setTypecode(String typecode) {
    
    
    
    this.typecode = typecode;
  }


  public GoalsGetGoalResponse status(String status) {
    
    
    
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "string", value = "")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    
    
    
    this.status = status;
  }


  public GoalsGetGoalResponse state(String state) {
    
    
    
    
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "string", value = "")

  public String getState() {
    return state;
  }


  public void setState(String state) {
    
    
    
    this.state = state;
  }


  public GoalsGetGoalResponse predictiveIndex(String predictiveIndex) {
    
    
    
    
    this.predictiveIndex = predictiveIndex;
    return this;
  }

   /**
   * Get predictiveIndex
   * @return predictiveIndex
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "string", value = "")

  public String getPredictiveIndex() {
    return predictiveIndex;
  }


  public void setPredictiveIndex(String predictiveIndex) {
    
    
    
    this.predictiveIndex = predictiveIndex;
  }


  public GoalsGetGoalResponse objectiveId(String objectiveId) {
    
    
    
    
    this.objectiveId = objectiveId;
    return this;
  }

   /**
   * Get objectiveId
   * @return objectiveId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "int", value = "")

  public String getObjectiveId() {
    return objectiveId;
  }


  public void setObjectiveId(String objectiveId) {
    
    
    
    this.objectiveId = objectiveId;
  }


  public GoalsGetGoalResponse cid(String cid) {
    
    
    
    
    this.cid = cid;
    return this;
  }

   /**
   * Get cid
   * @return cid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "int", value = "")

  public String getCid() {
    return cid;
  }


  public void setCid(String cid) {
    
    
    
    this.cid = cid;
  }


  public GoalsGetGoalResponse disposition(String disposition) {
    
    
    
    
    this.disposition = disposition;
    return this;
  }

   /**
   * Get disposition
   * @return disposition
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "string", value = "")

  public String getDisposition() {
    return disposition;
  }


  public void setDisposition(String disposition) {
    
    
    
    this.disposition = disposition;
  }


  public GoalsGetGoalResponse units(String units) {
    
    
    
    
    this.units = units;
    return this;
  }

   /**
   * Get units
   * @return units
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "string", value = "")

  public String getUnits() {
    return units;
  }


  public void setUnits(String units) {
    
    
    
    this.units = units;
  }


  public GoalsGetGoalResponse assignedUserModel(GoalsGetGoalResponseAssignedUserModel assignedUserModel) {
    
    
    
    
    this.assignedUserModel = assignedUserModel;
    return this;
  }

   /**
   * Get assignedUserModel
   * @return assignedUserModel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GoalsGetGoalResponseAssignedUserModel getAssignedUserModel() {
    return assignedUserModel;
  }


  public void setAssignedUserModel(GoalsGetGoalResponseAssignedUserModel assignedUserModel) {
    
    
    
    this.assignedUserModel = assignedUserModel;
  }


  public GoalsGetGoalResponse reviewerUserModel(GoalsGetGoalResponseReviewerUserModel reviewerUserModel) {
    
    
    
    
    this.reviewerUserModel = reviewerUserModel;
    return this;
  }

   /**
   * Get reviewerUserModel
   * @return reviewerUserModel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GoalsGetGoalResponseReviewerUserModel getReviewerUserModel() {
    return reviewerUserModel;
  }


  public void setReviewerUserModel(GoalsGetGoalResponseReviewerUserModel reviewerUserModel) {
    
    
    
    this.reviewerUserModel = reviewerUserModel;
  }


  public GoalsGetGoalResponse goalCollaborationModel(List<GoalsGetGoalResponseGoalCollaborationModelInner> goalCollaborationModel) {
    
    
    
    
    this.goalCollaborationModel = goalCollaborationModel;
    return this;
  }

  public GoalsGetGoalResponse addGoalCollaborationModelItem(GoalsGetGoalResponseGoalCollaborationModelInner goalCollaborationModelItem) {
    if (this.goalCollaborationModel == null) {
      this.goalCollaborationModel = new ArrayList<>();
    }
    this.goalCollaborationModel.add(goalCollaborationModelItem);
    return this;
  }

   /**
   * Get goalCollaborationModel
   * @return goalCollaborationModel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<GoalsGetGoalResponseGoalCollaborationModelInner> getGoalCollaborationModel() {
    return goalCollaborationModel;
  }


  public void setGoalCollaborationModel(List<GoalsGetGoalResponseGoalCollaborationModelInner> goalCollaborationModel) {
    
    
    
    this.goalCollaborationModel = goalCollaborationModel;
  }


  public GoalsGetGoalResponse crediteatets(String crediteatets) {
    
    
    
    
    this.crediteatets = crediteatets;
    return this;
  }

   /**
   * Get crediteatets
   * @return crediteatets
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "int", value = "")

  public String getCrediteatets() {
    return crediteatets;
  }


  public void setCrediteatets(String crediteatets) {
    
    
    
    this.crediteatets = crediteatets;
  }


  public GoalsGetGoalResponse commentCrediteatets(String commentCrediteatets) {
    
    
    
    
    this.commentCrediteatets = commentCrediteatets;
    return this;
  }

   /**
   * Get commentCrediteatets
   * @return commentCrediteatets
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "int", value = "")

  public String getCommentCrediteatets() {
    return commentCrediteatets;
  }


  public void setCommentCrediteatets(String commentCrediteatets) {
    
    
    
    this.commentCrediteatets = commentCrediteatets;
  }


  public GoalsGetGoalResponse commentDescription(String commentDescription) {
    
    
    
    
    this.commentDescription = commentDescription;
    return this;
  }

   /**
   * Get commentDescription
   * @return commentDescription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "string", value = "")

  public String getCommentDescription() {
    return commentDescription;
  }


  public void setCommentDescription(String commentDescription) {
    
    
    
    this.commentDescription = commentDescription;
  }


  public GoalsGetGoalResponse uname(String uname) {
    
    
    
    
    this.uname = uname;
    return this;
  }

   /**
   * Get uname
   * @return uname
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "string", value = "")

  public String getUname() {
    return uname;
  }


  public void setUname(String uname) {
    
    
    
    this.uname = uname;
  }


  public GoalsGetGoalResponse hasGoalApprovalPermission(String hasGoalApprovalPermission) {
    
    
    
    
    this.hasGoalApprovalPermission = hasGoalApprovalPermission;
    return this;
  }

   /**
   * Get hasGoalApprovalPermission
   * @return hasGoalApprovalPermission
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "boolean", value = "")

  public String getHasGoalApprovalPermission() {
    return hasGoalApprovalPermission;
  }


  public void setHasGoalApprovalPermission(String hasGoalApprovalPermission) {
    
    
    
    this.hasGoalApprovalPermission = hasGoalApprovalPermission;
  }


  public GoalsGetGoalResponse begindate(String begindate) {
    
    
    
    
    this.begindate = begindate;
    return this;
  }

   /**
   * Get begindate
   * @return begindate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "date", value = "")

  public String getBegindate() {
    return begindate;
  }


  public void setBegindate(String begindate) {
    
    
    
    this.begindate = begindate;
  }


  public GoalsGetGoalResponse goalWeightage(String goalWeightage) {
    
    
    
    
    this.goalWeightage = goalWeightage;
    return this;
  }

   /**
   * Get goalWeightage
   * @return goalWeightage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "float", value = "")

  public String getGoalWeightage() {
    return goalWeightage;
  }


  public void setGoalWeightage(String goalWeightage) {
    
    
    
    this.goalWeightage = goalWeightage;
  }


  public GoalsGetGoalResponse createuserid(String createuserid) {
    
    
    
    
    this.createuserid = createuserid;
    return this;
  }

   /**
   * Get createuserid
   * @return createuserid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "int", value = "")

  public String getCreateuserid() {
    return createuserid;
  }


  public void setCreateuserid(String createuserid) {
    
    
    
    this.createuserid = createuserid;
  }


  public GoalsGetGoalResponse createts(Integer createts) {
    
    
    
    
    this.createts = createts;
    return this;
  }

   /**
   * Get createts
   * @return createts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1661358176000", value = "")

  public Integer getCreatets() {
    return createts;
  }


  public void setCreatets(Integer createts) {
    
    
    
    this.createts = createts;
  }


  public GoalsGetGoalResponse projectModel(GoalsGetGoalResponseProjectModel projectModel) {
    
    
    
    
    this.projectModel = projectModel;
    return this;
  }

   /**
   * Get projectModel
   * @return projectModel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GoalsGetGoalResponseProjectModel getProjectModel() {
    return projectModel;
  }


  public void setProjectModel(GoalsGetGoalResponseProjectModel projectModel) {
    
    
    
    this.projectModel = projectModel;
  }


  public GoalsGetGoalResponse goalTypeModel(GoalsGetGoalResponseGoalTypeModel goalTypeModel) {
    
    
    
    
    this.goalTypeModel = goalTypeModel;
    return this;
  }

   /**
   * Get goalTypeModel
   * @return goalTypeModel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GoalsGetGoalResponseGoalTypeModel getGoalTypeModel() {
    return goalTypeModel;
  }


  public void setGoalTypeModel(GoalsGetGoalResponseGoalTypeModel goalTypeModel) {
    
    
    
    this.goalTypeModel = goalTypeModel;
  }


  public GoalsGetGoalResponse parentGoalId(String parentGoalId) {
    
    
    
    
    this.parentGoalId = parentGoalId;
    return this;
  }

   /**
   * Get parentGoalId
   * @return parentGoalId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "int", value = "")

  public String getParentGoalId() {
    return parentGoalId;
  }


  public void setParentGoalId(String parentGoalId) {
    
    
    
    this.parentGoalId = parentGoalId;
  }


  public GoalsGetGoalResponse id(String id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "int", value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    
    
    
    this.id = id;
  }


  public GoalsGetGoalResponse createUserId(String createUserId) {
    
    
    
    
    this.createUserId = createUserId;
    return this;
  }

   /**
   * Get createUserId
   * @return createUserId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "int", value = "")

  public String getCreateUserId() {
    return createUserId;
  }


  public void setCreateUserId(String createUserId) {
    
    
    
    this.createUserId = createUserId;
  }


  public GoalsGetGoalResponse lastUpdateUserId(String lastUpdateUserId) {
    
    
    
    
    this.lastUpdateUserId = lastUpdateUserId;
    return this;
  }

   /**
   * Get lastUpdateUserId
   * @return lastUpdateUserId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "int", value = "")

  public String getLastUpdateUserId() {
    return lastUpdateUserId;
  }


  public void setLastUpdateUserId(String lastUpdateUserId) {
    
    
    
    this.lastUpdateUserId = lastUpdateUserId;
  }


  public GoalsGetGoalResponse projectid(String projectid) {
    
    
    
    
    this.projectid = projectid;
    return this;
  }

   /**
   * Get projectid
   * @return projectid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "int", value = "")

  public String getProjectid() {
    return projectid;
  }


  public void setProjectid(String projectid) {
    
    
    
    this.projectid = projectid;
  }


  public GoalsGetGoalResponse targetdate(String targetdate) {
    
    
    
    
    this.targetdate = targetdate;
    return this;
  }

   /**
   * Get targetdate
   * @return targetdate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "date", value = "")

  public String getTargetdate() {
    return targetdate;
  }


  public void setTargetdate(String targetdate) {
    
    
    
    this.targetdate = targetdate;
  }


  public GoalsGetGoalResponse initialvalue(String initialvalue) {
    
    
    
    
    this.initialvalue = initialvalue;
    return this;
  }

   /**
   * Get initialvalue
   * @return initialvalue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "double", value = "")

  public String getInitialvalue() {
    return initialvalue;
  }


  public void setInitialvalue(String initialvalue) {
    
    
    
    this.initialvalue = initialvalue;
  }


  public GoalsGetGoalResponse currentvalue(String currentvalue) {
    
    
    
    
    this.currentvalue = currentvalue;
    return this;
  }

   /**
   * Get currentvalue
   * @return currentvalue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "double", value = "")

  public String getCurrentvalue() {
    return currentvalue;
  }


  public void setCurrentvalue(String currentvalue) {
    
    
    
    this.currentvalue = currentvalue;
  }


  public GoalsGetGoalResponse goalvalue(String goalvalue) {
    
    
    
    
    this.goalvalue = goalvalue;
    return this;
  }

   /**
   * Get goalvalue
   * @return goalvalue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "double", value = "")

  public String getGoalvalue() {
    return goalvalue;
  }


  public void setGoalvalue(String goalvalue) {
    
    
    
    this.goalvalue = goalvalue;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the GoalsGetGoalResponse instance itself
   */
  public GoalsGetGoalResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GoalsGetGoalResponse goalsGetGoalResponse = (GoalsGetGoalResponse) o;
    return Objects.equals(this.summary, goalsGetGoalResponse.summary) &&
        Objects.equals(this.description, goalsGetGoalResponse.description) &&
        Objects.equals(this.goalId, goalsGetGoalResponse.goalId) &&
        Objects.equals(this.additive, goalsGetGoalResponse.additive) &&
        Objects.equals(this.visibleToDirectReports, goalsGetGoalResponse.visibleToDirectReports) &&
        Objects.equals(this.freezeGoal, goalsGetGoalResponse.freezeGoal) &&
        Objects.equals(this.isForward, goalsGetGoalResponse.isForward) &&
        Objects.equals(this.companyGoal, goalsGetGoalResponse.companyGoal) &&
        Objects.equals(this.elapsedTimeRatio, goalsGetGoalResponse.elapsedTimeRatio) &&
        Objects.equals(this.completionRatio, goalsGetGoalResponse.completionRatio) &&
        Objects.equals(this.progressRatio, goalsGetGoalResponse.progressRatio) &&
        Objects.equals(this.typecode, goalsGetGoalResponse.typecode) &&
        Objects.equals(this.status, goalsGetGoalResponse.status) &&
        Objects.equals(this.state, goalsGetGoalResponse.state) &&
        Objects.equals(this.predictiveIndex, goalsGetGoalResponse.predictiveIndex) &&
        Objects.equals(this.objectiveId, goalsGetGoalResponse.objectiveId) &&
        Objects.equals(this.cid, goalsGetGoalResponse.cid) &&
        Objects.equals(this.disposition, goalsGetGoalResponse.disposition) &&
        Objects.equals(this.units, goalsGetGoalResponse.units) &&
        Objects.equals(this.assignedUserModel, goalsGetGoalResponse.assignedUserModel) &&
        Objects.equals(this.reviewerUserModel, goalsGetGoalResponse.reviewerUserModel) &&
        Objects.equals(this.goalCollaborationModel, goalsGetGoalResponse.goalCollaborationModel) &&
        Objects.equals(this.crediteatets, goalsGetGoalResponse.crediteatets) &&
        Objects.equals(this.commentCrediteatets, goalsGetGoalResponse.commentCrediteatets) &&
        Objects.equals(this.commentDescription, goalsGetGoalResponse.commentDescription) &&
        Objects.equals(this.uname, goalsGetGoalResponse.uname) &&
        Objects.equals(this.hasGoalApprovalPermission, goalsGetGoalResponse.hasGoalApprovalPermission) &&
        Objects.equals(this.begindate, goalsGetGoalResponse.begindate) &&
        Objects.equals(this.goalWeightage, goalsGetGoalResponse.goalWeightage) &&
        Objects.equals(this.createuserid, goalsGetGoalResponse.createuserid) &&
        Objects.equals(this.createts, goalsGetGoalResponse.createts) &&
        Objects.equals(this.projectModel, goalsGetGoalResponse.projectModel) &&
        Objects.equals(this.goalTypeModel, goalsGetGoalResponse.goalTypeModel) &&
        Objects.equals(this.parentGoalId, goalsGetGoalResponse.parentGoalId) &&
        Objects.equals(this.id, goalsGetGoalResponse.id) &&
        Objects.equals(this.createUserId, goalsGetGoalResponse.createUserId) &&
        Objects.equals(this.lastUpdateUserId, goalsGetGoalResponse.lastUpdateUserId) &&
        Objects.equals(this.projectid, goalsGetGoalResponse.projectid) &&
        Objects.equals(this.targetdate, goalsGetGoalResponse.targetdate) &&
        Objects.equals(this.initialvalue, goalsGetGoalResponse.initialvalue) &&
        Objects.equals(this.currentvalue, goalsGetGoalResponse.currentvalue) &&
        Objects.equals(this.goalvalue, goalsGetGoalResponse.goalvalue)&&
        Objects.equals(this.additionalProperties, goalsGetGoalResponse.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(summary, description, goalId, additive, visibleToDirectReports, freezeGoal, isForward, companyGoal, elapsedTimeRatio, completionRatio, progressRatio, typecode, status, state, predictiveIndex, objectiveId, cid, disposition, units, assignedUserModel, reviewerUserModel, goalCollaborationModel, crediteatets, commentCrediteatets, commentDescription, uname, hasGoalApprovalPermission, begindate, goalWeightage, createuserid, createts, projectModel, goalTypeModel, parentGoalId, id, createUserId, lastUpdateUserId, projectid, targetdate, initialvalue, currentvalue, goalvalue, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GoalsGetGoalResponse {\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    goalId: ").append(toIndentedString(goalId)).append("\n");
    sb.append("    additive: ").append(toIndentedString(additive)).append("\n");
    sb.append("    visibleToDirectReports: ").append(toIndentedString(visibleToDirectReports)).append("\n");
    sb.append("    freezeGoal: ").append(toIndentedString(freezeGoal)).append("\n");
    sb.append("    isForward: ").append(toIndentedString(isForward)).append("\n");
    sb.append("    companyGoal: ").append(toIndentedString(companyGoal)).append("\n");
    sb.append("    elapsedTimeRatio: ").append(toIndentedString(elapsedTimeRatio)).append("\n");
    sb.append("    completionRatio: ").append(toIndentedString(completionRatio)).append("\n");
    sb.append("    progressRatio: ").append(toIndentedString(progressRatio)).append("\n");
    sb.append("    typecode: ").append(toIndentedString(typecode)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    predictiveIndex: ").append(toIndentedString(predictiveIndex)).append("\n");
    sb.append("    objectiveId: ").append(toIndentedString(objectiveId)).append("\n");
    sb.append("    cid: ").append(toIndentedString(cid)).append("\n");
    sb.append("    disposition: ").append(toIndentedString(disposition)).append("\n");
    sb.append("    units: ").append(toIndentedString(units)).append("\n");
    sb.append("    assignedUserModel: ").append(toIndentedString(assignedUserModel)).append("\n");
    sb.append("    reviewerUserModel: ").append(toIndentedString(reviewerUserModel)).append("\n");
    sb.append("    goalCollaborationModel: ").append(toIndentedString(goalCollaborationModel)).append("\n");
    sb.append("    crediteatets: ").append(toIndentedString(crediteatets)).append("\n");
    sb.append("    commentCrediteatets: ").append(toIndentedString(commentCrediteatets)).append("\n");
    sb.append("    commentDescription: ").append(toIndentedString(commentDescription)).append("\n");
    sb.append("    uname: ").append(toIndentedString(uname)).append("\n");
    sb.append("    hasGoalApprovalPermission: ").append(toIndentedString(hasGoalApprovalPermission)).append("\n");
    sb.append("    begindate: ").append(toIndentedString(begindate)).append("\n");
    sb.append("    goalWeightage: ").append(toIndentedString(goalWeightage)).append("\n");
    sb.append("    createuserid: ").append(toIndentedString(createuserid)).append("\n");
    sb.append("    createts: ").append(toIndentedString(createts)).append("\n");
    sb.append("    projectModel: ").append(toIndentedString(projectModel)).append("\n");
    sb.append("    goalTypeModel: ").append(toIndentedString(goalTypeModel)).append("\n");
    sb.append("    parentGoalId: ").append(toIndentedString(parentGoalId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    createUserId: ").append(toIndentedString(createUserId)).append("\n");
    sb.append("    lastUpdateUserId: ").append(toIndentedString(lastUpdateUserId)).append("\n");
    sb.append("    projectid: ").append(toIndentedString(projectid)).append("\n");
    sb.append("    targetdate: ").append(toIndentedString(targetdate)).append("\n");
    sb.append("    initialvalue: ").append(toIndentedString(initialvalue)).append("\n");
    sb.append("    currentvalue: ").append(toIndentedString(currentvalue)).append("\n");
    sb.append("    goalvalue: ").append(toIndentedString(goalvalue)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("summary");
    openapiFields.add("description");
    openapiFields.add("goalId");
    openapiFields.add("additive");
    openapiFields.add("visibleToDirectReports");
    openapiFields.add("freezeGoal");
    openapiFields.add("isForward");
    openapiFields.add("companyGoal");
    openapiFields.add("elapsedTimeRatio");
    openapiFields.add("completionRatio");
    openapiFields.add("progressRatio");
    openapiFields.add("typecode");
    openapiFields.add("status");
    openapiFields.add("state");
    openapiFields.add("predictiveIndex");
    openapiFields.add("objectiveId");
    openapiFields.add("cid");
    openapiFields.add("disposition");
    openapiFields.add("units");
    openapiFields.add("assignedUserModel");
    openapiFields.add("reviewerUserModel");
    openapiFields.add("goalCollaborationModel");
    openapiFields.add("crediteatets");
    openapiFields.add("commentCrediteatets");
    openapiFields.add("commentDescription");
    openapiFields.add("uname");
    openapiFields.add("hasGoalApprovalPermission");
    openapiFields.add("begindate");
    openapiFields.add("goalWeightage");
    openapiFields.add("createuserid");
    openapiFields.add("createts");
    openapiFields.add("projectModel");
    openapiFields.add("goalTypeModel");
    openapiFields.add("parentGoalId");
    openapiFields.add("id");
    openapiFields.add("createUserId");
    openapiFields.add("lastUpdateUserId");
    openapiFields.add("projectid");
    openapiFields.add("targetdate");
    openapiFields.add("initialvalue");
    openapiFields.add("currentvalue");
    openapiFields.add("goalvalue");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to GoalsGetGoalResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!GoalsGetGoalResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GoalsGetGoalResponse is not found in the empty JSON string", GoalsGetGoalResponse.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("summary") != null && !jsonObj.get("summary").isJsonNull()) && !jsonObj.get("summary").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `summary` to be a primitive type in the JSON string but got `%s`", jsonObj.get("summary").toString()));
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("goalId") != null && !jsonObj.get("goalId").isJsonNull()) && !jsonObj.get("goalId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `goalId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("goalId").toString()));
      }
      if ((jsonObj.get("additive") != null && !jsonObj.get("additive").isJsonNull()) && !jsonObj.get("additive").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `additive` to be a primitive type in the JSON string but got `%s`", jsonObj.get("additive").toString()));
      }
      if ((jsonObj.get("visibleToDirectReports") != null && !jsonObj.get("visibleToDirectReports").isJsonNull()) && !jsonObj.get("visibleToDirectReports").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `visibleToDirectReports` to be a primitive type in the JSON string but got `%s`", jsonObj.get("visibleToDirectReports").toString()));
      }
      if ((jsonObj.get("freezeGoal") != null && !jsonObj.get("freezeGoal").isJsonNull()) && !jsonObj.get("freezeGoal").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `freezeGoal` to be a primitive type in the JSON string but got `%s`", jsonObj.get("freezeGoal").toString()));
      }
      if ((jsonObj.get("isForward") != null && !jsonObj.get("isForward").isJsonNull()) && !jsonObj.get("isForward").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `isForward` to be a primitive type in the JSON string but got `%s`", jsonObj.get("isForward").toString()));
      }
      if ((jsonObj.get("companyGoal") != null && !jsonObj.get("companyGoal").isJsonNull()) && !jsonObj.get("companyGoal").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `companyGoal` to be a primitive type in the JSON string but got `%s`", jsonObj.get("companyGoal").toString()));
      }
      if ((jsonObj.get("elapsedTimeRatio") != null && !jsonObj.get("elapsedTimeRatio").isJsonNull()) && !jsonObj.get("elapsedTimeRatio").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `elapsedTimeRatio` to be a primitive type in the JSON string but got `%s`", jsonObj.get("elapsedTimeRatio").toString()));
      }
      if ((jsonObj.get("completionRatio") != null && !jsonObj.get("completionRatio").isJsonNull()) && !jsonObj.get("completionRatio").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `completionRatio` to be a primitive type in the JSON string but got `%s`", jsonObj.get("completionRatio").toString()));
      }
      if ((jsonObj.get("progressRatio") != null && !jsonObj.get("progressRatio").isJsonNull()) && !jsonObj.get("progressRatio").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `progressRatio` to be a primitive type in the JSON string but got `%s`", jsonObj.get("progressRatio").toString()));
      }
      if ((jsonObj.get("typecode") != null && !jsonObj.get("typecode").isJsonNull()) && !jsonObj.get("typecode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `typecode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("typecode").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if ((jsonObj.get("state") != null && !jsonObj.get("state").isJsonNull()) && !jsonObj.get("state").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `state` to be a primitive type in the JSON string but got `%s`", jsonObj.get("state").toString()));
      }
      if ((jsonObj.get("predictiveIndex") != null && !jsonObj.get("predictiveIndex").isJsonNull()) && !jsonObj.get("predictiveIndex").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `predictiveIndex` to be a primitive type in the JSON string but got `%s`", jsonObj.get("predictiveIndex").toString()));
      }
      if ((jsonObj.get("objectiveId") != null && !jsonObj.get("objectiveId").isJsonNull()) && !jsonObj.get("objectiveId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `objectiveId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("objectiveId").toString()));
      }
      if ((jsonObj.get("cid") != null && !jsonObj.get("cid").isJsonNull()) && !jsonObj.get("cid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cid").toString()));
      }
      if ((jsonObj.get("disposition") != null && !jsonObj.get("disposition").isJsonNull()) && !jsonObj.get("disposition").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `disposition` to be a primitive type in the JSON string but got `%s`", jsonObj.get("disposition").toString()));
      }
      if ((jsonObj.get("units") != null && !jsonObj.get("units").isJsonNull()) && !jsonObj.get("units").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `units` to be a primitive type in the JSON string but got `%s`", jsonObj.get("units").toString()));
      }
      // validate the optional field `assignedUserModel`
      if (jsonObj.get("assignedUserModel") != null && !jsonObj.get("assignedUserModel").isJsonNull()) {
        GoalsGetGoalResponseAssignedUserModel.validateJsonObject(jsonObj.getAsJsonObject("assignedUserModel"));
      }
      // validate the optional field `reviewerUserModel`
      if (jsonObj.get("reviewerUserModel") != null && !jsonObj.get("reviewerUserModel").isJsonNull()) {
        GoalsGetGoalResponseReviewerUserModel.validateJsonObject(jsonObj.getAsJsonObject("reviewerUserModel"));
      }
      if (jsonObj.get("goalCollaborationModel") != null && !jsonObj.get("goalCollaborationModel").isJsonNull()) {
        JsonArray jsonArraygoalCollaborationModel = jsonObj.getAsJsonArray("goalCollaborationModel");
        if (jsonArraygoalCollaborationModel != null) {
          // ensure the json data is an array
          if (!jsonObj.get("goalCollaborationModel").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `goalCollaborationModel` to be an array in the JSON string but got `%s`", jsonObj.get("goalCollaborationModel").toString()));
          }

          // validate the optional field `goalCollaborationModel` (array)
          for (int i = 0; i < jsonArraygoalCollaborationModel.size(); i++) {
            GoalsGetGoalResponseGoalCollaborationModelInner.validateJsonObject(jsonArraygoalCollaborationModel.get(i).getAsJsonObject());
          };
        }
      }
      if ((jsonObj.get("crediteatets") != null && !jsonObj.get("crediteatets").isJsonNull()) && !jsonObj.get("crediteatets").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `crediteatets` to be a primitive type in the JSON string but got `%s`", jsonObj.get("crediteatets").toString()));
      }
      if ((jsonObj.get("commentCrediteatets") != null && !jsonObj.get("commentCrediteatets").isJsonNull()) && !jsonObj.get("commentCrediteatets").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `commentCrediteatets` to be a primitive type in the JSON string but got `%s`", jsonObj.get("commentCrediteatets").toString()));
      }
      if ((jsonObj.get("commentDescription") != null && !jsonObj.get("commentDescription").isJsonNull()) && !jsonObj.get("commentDescription").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `commentDescription` to be a primitive type in the JSON string but got `%s`", jsonObj.get("commentDescription").toString()));
      }
      if ((jsonObj.get("uname") != null && !jsonObj.get("uname").isJsonNull()) && !jsonObj.get("uname").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `uname` to be a primitive type in the JSON string but got `%s`", jsonObj.get("uname").toString()));
      }
      if ((jsonObj.get("hasGoalApprovalPermission") != null && !jsonObj.get("hasGoalApprovalPermission").isJsonNull()) && !jsonObj.get("hasGoalApprovalPermission").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `hasGoalApprovalPermission` to be a primitive type in the JSON string but got `%s`", jsonObj.get("hasGoalApprovalPermission").toString()));
      }
      if ((jsonObj.get("begindate") != null && !jsonObj.get("begindate").isJsonNull()) && !jsonObj.get("begindate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `begindate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("begindate").toString()));
      }
      if ((jsonObj.get("goalWeightage") != null && !jsonObj.get("goalWeightage").isJsonNull()) && !jsonObj.get("goalWeightage").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `goalWeightage` to be a primitive type in the JSON string but got `%s`", jsonObj.get("goalWeightage").toString()));
      }
      if ((jsonObj.get("createuserid") != null && !jsonObj.get("createuserid").isJsonNull()) && !jsonObj.get("createuserid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `createuserid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("createuserid").toString()));
      }
      // validate the optional field `projectModel`
      if (jsonObj.get("projectModel") != null && !jsonObj.get("projectModel").isJsonNull()) {
        GoalsGetGoalResponseProjectModel.validateJsonObject(jsonObj.getAsJsonObject("projectModel"));
      }
      // validate the optional field `goalTypeModel`
      if (jsonObj.get("goalTypeModel") != null && !jsonObj.get("goalTypeModel").isJsonNull()) {
        GoalsGetGoalResponseGoalTypeModel.validateJsonObject(jsonObj.getAsJsonObject("goalTypeModel"));
      }
      if ((jsonObj.get("parentGoalId") != null && !jsonObj.get("parentGoalId").isJsonNull()) && !jsonObj.get("parentGoalId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `parentGoalId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("parentGoalId").toString()));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("createUserId") != null && !jsonObj.get("createUserId").isJsonNull()) && !jsonObj.get("createUserId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `createUserId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("createUserId").toString()));
      }
      if ((jsonObj.get("lastUpdateUserId") != null && !jsonObj.get("lastUpdateUserId").isJsonNull()) && !jsonObj.get("lastUpdateUserId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `lastUpdateUserId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("lastUpdateUserId").toString()));
      }
      if ((jsonObj.get("projectid") != null && !jsonObj.get("projectid").isJsonNull()) && !jsonObj.get("projectid").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `projectid` to be a primitive type in the JSON string but got `%s`", jsonObj.get("projectid").toString()));
      }
      if ((jsonObj.get("targetdate") != null && !jsonObj.get("targetdate").isJsonNull()) && !jsonObj.get("targetdate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `targetdate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("targetdate").toString()));
      }
      if ((jsonObj.get("initialvalue") != null && !jsonObj.get("initialvalue").isJsonNull()) && !jsonObj.get("initialvalue").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `initialvalue` to be a primitive type in the JSON string but got `%s`", jsonObj.get("initialvalue").toString()));
      }
      if ((jsonObj.get("currentvalue") != null && !jsonObj.get("currentvalue").isJsonNull()) && !jsonObj.get("currentvalue").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `currentvalue` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currentvalue").toString()));
      }
      if ((jsonObj.get("goalvalue") != null && !jsonObj.get("goalvalue").isJsonNull()) && !jsonObj.get("goalvalue").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `goalvalue` to be a primitive type in the JSON string but got `%s`", jsonObj.get("goalvalue").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GoalsGetGoalResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GoalsGetGoalResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GoalsGetGoalResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GoalsGetGoalResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<GoalsGetGoalResponse>() {
           @Override
           public void write(JsonWriter out, GoalsGetGoalResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public GoalsGetGoalResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             GoalsGetGoalResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GoalsGetGoalResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GoalsGetGoalResponse
  * @throws IOException if the JSON string is invalid with respect to GoalsGetGoalResponse
  */
  public static GoalsGetGoalResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GoalsGetGoalResponse.class);
  }

 /**
  * Convert an instance of GoalsGetGoalResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

