/*
 * Expense Reports
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PtoPolicyApprovalFlowModel;
import com.konfigthis.client.model.PtoPolicyChainModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.sql.Timestamp;
import java.time.LocalDate;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * PtoPolicyModel
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class PtoPolicyModel {
  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_ACCRUAL_RATE_ANNUAL = "accrualRateAnnual";
  @SerializedName(SERIALIZED_NAME_ACCRUAL_RATE_ANNUAL)
  private Float accrualRateAnnual;

  public static final String SERIALIZED_NAME_ACCRUAL_RATE_ANNUAL_UNIT = "accrualRateAnnualUnit";
  @SerializedName(SERIALIZED_NAME_ACCRUAL_RATE_ANNUAL_UNIT)
  private Double accrualRateAnnualUnit;

  public static final String SERIALIZED_NAME_ACCRUAL_RATE_HOURS = "accrualRateHours";
  @SerializedName(SERIALIZED_NAME_ACCRUAL_RATE_HOURS)
  private Float accrualRateHours;

  public static final String SERIALIZED_NAME_ACCRUAL_RATE_UNIT = "accrualRateUnit";
  @SerializedName(SERIALIZED_NAME_ACCRUAL_RATE_UNIT)
  private Double accrualRateUnit;

  public static final String SERIALIZED_NAME_ACCRUAL_THRESHOLD_WEEKS = "accrualThresholdWeeks";
  @SerializedName(SERIALIZED_NAME_ACCRUAL_THRESHOLD_WEEKS)
  private Integer accrualThresholdWeeks;

  public static final String SERIALIZED_NAME_ACCRUAL_TIME = "accrualTime";
  @SerializedName(SERIALIZED_NAME_ACCRUAL_TIME)
  private Integer accrualTime;

  public static final String SERIALIZED_NAME_ACCRUAL_TIME_SPAN = "accrualTimeSpan";
  @SerializedName(SERIALIZED_NAME_ACCRUAL_TIME_SPAN)
  private String accrualTimeSpan;

  public static final String SERIALIZED_NAME_ACCRUALTYPE = "accrualtype";
  @SerializedName(SERIALIZED_NAME_ACCRUALTYPE)
  private String accrualtype;

  public static final String SERIALIZED_NAME_ALLOW_ACCRUAL_RATE_OVERRIDE = "allowAccrualRateOverride";
  @SerializedName(SERIALIZED_NAME_ALLOW_ACCRUAL_RATE_OVERRIDE)
  private Integer allowAccrualRateOverride;

  public static final String SERIALIZED_NAME_ALLOW_REQUEST_BEYOND_BAL = "allowRequestBeyondBal";
  @SerializedName(SERIALIZED_NAME_ALLOW_REQUEST_BEYOND_BAL)
  private Integer allowRequestBeyondBal;

  public static final String SERIALIZED_NAME_APPLICABILITY = "applicability";
  @SerializedName(SERIALIZED_NAME_APPLICABILITY)
  private Integer applicability;

  public static final String SERIALIZED_NAME_BONUS = "bonus";
  @SerializedName(SERIALIZED_NAME_BONUS)
  private Float bonus;

  public static final String SERIALIZED_NAME_BONUS_MAX = "bonusMax";
  @SerializedName(SERIALIZED_NAME_BONUS_MAX)
  private Float bonusMax;

  public static final String SERIALIZED_NAME_CARRYOVER_DATE = "carryoverDate";
  @SerializedName(SERIALIZED_NAME_CARRYOVER_DATE)
  private LocalDate carryoverDate;

  public static final String SERIALIZED_NAME_CARRYOVER_EXPIRATION_QUANTITY = "carryoverExpirationQuantity";
  @SerializedName(SERIALIZED_NAME_CARRYOVER_EXPIRATION_QUANTITY)
  private Integer carryoverExpirationQuantity;

  public static final String SERIALIZED_NAME_CARRYOVER_EXPIRATION_UNIT = "carryoverExpirationUnit";
  @SerializedName(SERIALIZED_NAME_CARRYOVER_EXPIRATION_UNIT)
  private String carryoverExpirationUnit;

  public static final String SERIALIZED_NAME_CID = "cid";
  @SerializedName(SERIALIZED_NAME_CID)
  private Integer cid;

  public static final String SERIALIZED_NAME_CREATE_USER_ID = "createUserId";
  @SerializedName(SERIALIZED_NAME_CREATE_USER_ID)
  private Integer createUserId;

  public static final String SERIALIZED_NAME_CREATETS = "createts";
  @SerializedName(SERIALIZED_NAME_CREATETS)
  private Timestamp createts;

  public static final String SERIALIZED_NAME_CUSTOM_ICON = "customIcon";
  @SerializedName(SERIALIZED_NAME_CUSTOM_ICON)
  private String customIcon;

  public static final String SERIALIZED_NAME_DAYS_DEFINITION = "daysDefinition";
  @SerializedName(SERIALIZED_NAME_DAYS_DEFINITION)
  private String daysDefinition;

  public static final String SERIALIZED_NAME_EFFECTIVE_DATE = "effectiveDate";
  @SerializedName(SERIALIZED_NAME_EFFECTIVE_DATE)
  private LocalDate effectiveDate;

  public static final String SERIALIZED_NAME_EXPIRATION_DATE = "expirationDate";
  @SerializedName(SERIALIZED_NAME_EXPIRATION_DATE)
  private LocalDate expirationDate;

  public static final String SERIALIZED_NAME_HALF_DAY_ALLOWED = "halfDayAllowed";
  @SerializedName(SERIALIZED_NAME_HALF_DAY_ALLOWED)
  private Integer halfDayAllowed;

  public static final String SERIALIZED_NAME_HAS_ASSIGNMENT = "hasAssignment";
  @SerializedName(SERIALIZED_NAME_HAS_ASSIGNMENT)
  private Boolean hasAssignment;

  public static final String SERIALIZED_NAME_ICON = "icon";
  @SerializedName(SERIALIZED_NAME_ICON)
  private String icon;

  public static final String SERIALIZED_NAME_IS_ACCRUED = "isAccrued";
  @SerializedName(SERIALIZED_NAME_IS_ACCRUED)
  private String isAccrued;

  public static final String SERIALIZED_NAME_LAST_RUN = "lastRun";
  @SerializedName(SERIALIZED_NAME_LAST_RUN)
  private LocalDate lastRun;

  public static final String SERIALIZED_NAME_LEAVE_TYPE = "leaveType";
  @SerializedName(SERIALIZED_NAME_LEAVE_TYPE)
  private String leaveType;

  public static final String SERIALIZED_NAME_LEAVE_YEAR_START = "leaveYearStart";
  @SerializedName(SERIALIZED_NAME_LEAVE_YEAR_START)
  private String leaveYearStart;

  public static final String SERIALIZED_NAME_LEAVE_YEAR_START_DATE = "leaveYearStartDate";
  @SerializedName(SERIALIZED_NAME_LEAVE_YEAR_START_DATE)
  private LocalDate leaveYearStartDate;

  public static final String SERIALIZED_NAME_NEXT_RUN_DATE = "nextRunDate";
  @SerializedName(SERIALIZED_NAME_NEXT_RUN_DATE)
  private LocalDate nextRunDate;

  public static final String SERIALIZED_NAME_PAID = "paid";
  @SerializedName(SERIALIZED_NAME_PAID)
  private Integer paid;

  public static final String SERIALIZED_NAME_POLICY_NAME = "policyName";
  @SerializedName(SERIALIZED_NAME_POLICY_NAME)
  private String policyName;

  public static final String SERIALIZED_NAME_POLICYCONDITION = "policycondition";
  @SerializedName(SERIALIZED_NAME_POLICYCONDITION)
  private String policycondition;

  public static final String SERIALIZED_NAME_PRORATED = "prorated";
  @SerializedName(SERIALIZED_NAME_PRORATED)
  private Integer prorated;

  public static final String SERIALIZED_NAME_PTO_POLICY_APPROVAL_FLOW_MODEL = "ptoPolicyApprovalFlowModel";
  @SerializedName(SERIALIZED_NAME_PTO_POLICY_APPROVAL_FLOW_MODEL)
  private PtoPolicyApprovalFlowModel ptoPolicyApprovalFlowModel;

  public static final String SERIALIZED_NAME_PTO_POLICY_CHAIN_MODEL = "ptoPolicyChainModel";
  @SerializedName(SERIALIZED_NAME_PTO_POLICY_CHAIN_MODEL)
  private PtoPolicyChainModel ptoPolicyChainModel;

  public static final String SERIALIZED_NAME_PTO_POLICY_CHAIN_SEQ_ID = "ptoPolicyChainSeqId";
  @SerializedName(SERIALIZED_NAME_PTO_POLICY_CHAIN_SEQ_ID)
  private Integer ptoPolicyChainSeqId;

  public static final String SERIALIZED_NAME_PTO_POLICY_ID = "ptoPolicyId";
  @SerializedName(SERIALIZED_NAME_PTO_POLICY_ID)
  private Integer ptoPolicyId;

  public static final String SERIALIZED_NAME_ROLL_OVER_MAX = "rollOverMax";
  @SerializedName(SERIALIZED_NAME_ROLL_OVER_MAX)
  private Double rollOverMax;

  public static final String SERIALIZED_NAME_ROLL_OVER_PERCENTAGE = "rollOverPercentage";
  @SerializedName(SERIALIZED_NAME_ROLL_OVER_PERCENTAGE)
  private Double rollOverPercentage;

  public static final String SERIALIZED_NAME_SHOW_IN_CALENDAR = "showInCalendar";
  @SerializedName(SERIALIZED_NAME_SHOW_IN_CALENDAR)
  private Integer showInCalendar;

  public static final String SERIALIZED_NAME_TENURE_THRESHOLD = "tenureThreshold";
  @SerializedName(SERIALIZED_NAME_TENURE_THRESHOLD)
  private Float tenureThreshold;

  public static final String SERIALIZED_NAME_THRESHOLD_QUANTITY = "thresholdQuantity";
  @SerializedName(SERIALIZED_NAME_THRESHOLD_QUANTITY)
  private Integer thresholdQuantity;

  public static final String SERIALIZED_NAME_THRESHOLD_UNIT = "thresholdUnit";
  @SerializedName(SERIALIZED_NAME_THRESHOLD_UNIT)
  private String thresholdUnit;

  public static final String SERIALIZED_NAME_UNIT = "unit";
  @SerializedName(SERIALIZED_NAME_UNIT)
  private String unit;

  public PtoPolicyModel() {
  }

  public PtoPolicyModel description(String description) {
    
    
    
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    
    
    
    this.description = description;
  }


  public PtoPolicyModel accrualRateAnnual(Float accrualRateAnnual) {
    
    
    
    
    this.accrualRateAnnual = accrualRateAnnual;
    return this;
  }

   /**
   * Get accrualRateAnnual
   * @return accrualRateAnnual
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Float getAccrualRateAnnual() {
    return accrualRateAnnual;
  }


  public void setAccrualRateAnnual(Float accrualRateAnnual) {
    
    
    
    this.accrualRateAnnual = accrualRateAnnual;
  }


  public PtoPolicyModel accrualRateAnnualUnit(Double accrualRateAnnualUnit) {
    
    
    
    
    this.accrualRateAnnualUnit = accrualRateAnnualUnit;
    return this;
  }

   /**
   * Get accrualRateAnnualUnit
   * @return accrualRateAnnualUnit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getAccrualRateAnnualUnit() {
    return accrualRateAnnualUnit;
  }


  public void setAccrualRateAnnualUnit(Double accrualRateAnnualUnit) {
    
    
    
    this.accrualRateAnnualUnit = accrualRateAnnualUnit;
  }


  public PtoPolicyModel accrualRateHours(Float accrualRateHours) {
    
    
    
    
    this.accrualRateHours = accrualRateHours;
    return this;
  }

   /**
   * Get accrualRateHours
   * @return accrualRateHours
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Float getAccrualRateHours() {
    return accrualRateHours;
  }


  public void setAccrualRateHours(Float accrualRateHours) {
    
    
    
    this.accrualRateHours = accrualRateHours;
  }


  public PtoPolicyModel accrualRateUnit(Double accrualRateUnit) {
    
    
    
    
    this.accrualRateUnit = accrualRateUnit;
    return this;
  }

   /**
   * Get accrualRateUnit
   * @return accrualRateUnit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getAccrualRateUnit() {
    return accrualRateUnit;
  }


  public void setAccrualRateUnit(Double accrualRateUnit) {
    
    
    
    this.accrualRateUnit = accrualRateUnit;
  }


  public PtoPolicyModel accrualThresholdWeeks(Integer accrualThresholdWeeks) {
    
    
    
    
    this.accrualThresholdWeeks = accrualThresholdWeeks;
    return this;
  }

   /**
   * Get accrualThresholdWeeks
   * @return accrualThresholdWeeks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getAccrualThresholdWeeks() {
    return accrualThresholdWeeks;
  }


  public void setAccrualThresholdWeeks(Integer accrualThresholdWeeks) {
    
    
    
    this.accrualThresholdWeeks = accrualThresholdWeeks;
  }


  public PtoPolicyModel accrualTime(Integer accrualTime) {
    
    
    
    
    this.accrualTime = accrualTime;
    return this;
  }

   /**
   * Get accrualTime
   * @return accrualTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getAccrualTime() {
    return accrualTime;
  }


  public void setAccrualTime(Integer accrualTime) {
    
    
    
    this.accrualTime = accrualTime;
  }


  public PtoPolicyModel accrualTimeSpan(String accrualTimeSpan) {
    
    
    
    
    this.accrualTimeSpan = accrualTimeSpan;
    return this;
  }

   /**
   * Get accrualTimeSpan
   * @return accrualTimeSpan
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAccrualTimeSpan() {
    return accrualTimeSpan;
  }


  public void setAccrualTimeSpan(String accrualTimeSpan) {
    
    
    
    this.accrualTimeSpan = accrualTimeSpan;
  }


  public PtoPolicyModel accrualtype(String accrualtype) {
    
    
    
    
    this.accrualtype = accrualtype;
    return this;
  }

   /**
   * Get accrualtype
   * @return accrualtype
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAccrualtype() {
    return accrualtype;
  }


  public void setAccrualtype(String accrualtype) {
    
    
    
    this.accrualtype = accrualtype;
  }


  public PtoPolicyModel allowAccrualRateOverride(Integer allowAccrualRateOverride) {
    
    
    
    
    this.allowAccrualRateOverride = allowAccrualRateOverride;
    return this;
  }

   /**
   * Get allowAccrualRateOverride
   * @return allowAccrualRateOverride
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getAllowAccrualRateOverride() {
    return allowAccrualRateOverride;
  }


  public void setAllowAccrualRateOverride(Integer allowAccrualRateOverride) {
    
    
    
    this.allowAccrualRateOverride = allowAccrualRateOverride;
  }


  public PtoPolicyModel allowRequestBeyondBal(Integer allowRequestBeyondBal) {
    
    
    
    
    this.allowRequestBeyondBal = allowRequestBeyondBal;
    return this;
  }

   /**
   * Get allowRequestBeyondBal
   * @return allowRequestBeyondBal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getAllowRequestBeyondBal() {
    return allowRequestBeyondBal;
  }


  public void setAllowRequestBeyondBal(Integer allowRequestBeyondBal) {
    
    
    
    this.allowRequestBeyondBal = allowRequestBeyondBal;
  }


  public PtoPolicyModel applicability(Integer applicability) {
    
    
    
    
    this.applicability = applicability;
    return this;
  }

   /**
   * Get applicability
   * @return applicability
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getApplicability() {
    return applicability;
  }


  public void setApplicability(Integer applicability) {
    
    
    
    this.applicability = applicability;
  }


  public PtoPolicyModel bonus(Float bonus) {
    
    
    
    
    this.bonus = bonus;
    return this;
  }

   /**
   * Get bonus
   * @return bonus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Float getBonus() {
    return bonus;
  }


  public void setBonus(Float bonus) {
    
    
    
    this.bonus = bonus;
  }


  public PtoPolicyModel bonusMax(Float bonusMax) {
    
    
    
    
    this.bonusMax = bonusMax;
    return this;
  }

   /**
   * Get bonusMax
   * @return bonusMax
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Float getBonusMax() {
    return bonusMax;
  }


  public void setBonusMax(Float bonusMax) {
    
    
    
    this.bonusMax = bonusMax;
  }


  public PtoPolicyModel carryoverDate(LocalDate carryoverDate) {
    
    
    
    
    this.carryoverDate = carryoverDate;
    return this;
  }

   /**
   * Get carryoverDate
   * @return carryoverDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LocalDate getCarryoverDate() {
    return carryoverDate;
  }


  public void setCarryoverDate(LocalDate carryoverDate) {
    
    
    
    this.carryoverDate = carryoverDate;
  }


  public PtoPolicyModel carryoverExpirationQuantity(Integer carryoverExpirationQuantity) {
    
    
    
    
    this.carryoverExpirationQuantity = carryoverExpirationQuantity;
    return this;
  }

   /**
   * Get carryoverExpirationQuantity
   * @return carryoverExpirationQuantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getCarryoverExpirationQuantity() {
    return carryoverExpirationQuantity;
  }


  public void setCarryoverExpirationQuantity(Integer carryoverExpirationQuantity) {
    
    
    
    this.carryoverExpirationQuantity = carryoverExpirationQuantity;
  }


  public PtoPolicyModel carryoverExpirationUnit(String carryoverExpirationUnit) {
    
    
    
    
    this.carryoverExpirationUnit = carryoverExpirationUnit;
    return this;
  }

   /**
   * Get carryoverExpirationUnit
   * @return carryoverExpirationUnit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCarryoverExpirationUnit() {
    return carryoverExpirationUnit;
  }


  public void setCarryoverExpirationUnit(String carryoverExpirationUnit) {
    
    
    
    this.carryoverExpirationUnit = carryoverExpirationUnit;
  }


  public PtoPolicyModel cid(Integer cid) {
    
    
    
    
    this.cid = cid;
    return this;
  }

   /**
   * Get cid
   * @return cid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getCid() {
    return cid;
  }


  public void setCid(Integer cid) {
    
    
    
    this.cid = cid;
  }


  public PtoPolicyModel createUserId(Integer createUserId) {
    
    
    
    
    this.createUserId = createUserId;
    return this;
  }

   /**
   * Get createUserId
   * @return createUserId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getCreateUserId() {
    return createUserId;
  }


  public void setCreateUserId(Integer createUserId) {
    
    
    
    this.createUserId = createUserId;
  }


  public PtoPolicyModel createts(Timestamp createts) {
    
    
    
    
    this.createts = createts;
    return this;
  }

   /**
   * Get createts
   * @return createts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Timestamp getCreatets() {
    return createts;
  }


  public void setCreatets(Timestamp createts) {
    
    
    
    this.createts = createts;
  }


  public PtoPolicyModel customIcon(String customIcon) {
    
    
    
    
    this.customIcon = customIcon;
    return this;
  }

   /**
   * Get customIcon
   * @return customIcon
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCustomIcon() {
    return customIcon;
  }


  public void setCustomIcon(String customIcon) {
    
    
    
    this.customIcon = customIcon;
  }


  public PtoPolicyModel daysDefinition(String daysDefinition) {
    
    
    
    
    this.daysDefinition = daysDefinition;
    return this;
  }

   /**
   * Get daysDefinition
   * @return daysDefinition
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDaysDefinition() {
    return daysDefinition;
  }


  public void setDaysDefinition(String daysDefinition) {
    
    
    
    this.daysDefinition = daysDefinition;
  }


  public PtoPolicyModel effectiveDate(LocalDate effectiveDate) {
    
    
    
    
    this.effectiveDate = effectiveDate;
    return this;
  }

   /**
   * Get effectiveDate
   * @return effectiveDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LocalDate getEffectiveDate() {
    return effectiveDate;
  }


  public void setEffectiveDate(LocalDate effectiveDate) {
    
    
    
    this.effectiveDate = effectiveDate;
  }


  public PtoPolicyModel expirationDate(LocalDate expirationDate) {
    
    
    
    
    this.expirationDate = expirationDate;
    return this;
  }

   /**
   * Get expirationDate
   * @return expirationDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LocalDate getExpirationDate() {
    return expirationDate;
  }


  public void setExpirationDate(LocalDate expirationDate) {
    
    
    
    this.expirationDate = expirationDate;
  }


  public PtoPolicyModel halfDayAllowed(Integer halfDayAllowed) {
    
    
    
    
    this.halfDayAllowed = halfDayAllowed;
    return this;
  }

   /**
   * Get halfDayAllowed
   * @return halfDayAllowed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getHalfDayAllowed() {
    return halfDayAllowed;
  }


  public void setHalfDayAllowed(Integer halfDayAllowed) {
    
    
    
    this.halfDayAllowed = halfDayAllowed;
  }


  public PtoPolicyModel hasAssignment(Boolean hasAssignment) {
    
    
    
    
    this.hasAssignment = hasAssignment;
    return this;
  }

   /**
   * Get hasAssignment
   * @return hasAssignment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getHasAssignment() {
    return hasAssignment;
  }


  public void setHasAssignment(Boolean hasAssignment) {
    
    
    
    this.hasAssignment = hasAssignment;
  }


  public PtoPolicyModel icon(String icon) {
    
    
    
    
    this.icon = icon;
    return this;
  }

   /**
   * Get icon
   * @return icon
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getIcon() {
    return icon;
  }


  public void setIcon(String icon) {
    
    
    
    this.icon = icon;
  }


  public PtoPolicyModel isAccrued(String isAccrued) {
    
    
    
    
    this.isAccrued = isAccrued;
    return this;
  }

   /**
   * Get isAccrued
   * @return isAccrued
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getIsAccrued() {
    return isAccrued;
  }


  public void setIsAccrued(String isAccrued) {
    
    
    
    this.isAccrued = isAccrued;
  }


  public PtoPolicyModel lastRun(LocalDate lastRun) {
    
    
    
    
    this.lastRun = lastRun;
    return this;
  }

   /**
   * Get lastRun
   * @return lastRun
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LocalDate getLastRun() {
    return lastRun;
  }


  public void setLastRun(LocalDate lastRun) {
    
    
    
    this.lastRun = lastRun;
  }


  public PtoPolicyModel leaveType(String leaveType) {
    
    
    
    
    this.leaveType = leaveType;
    return this;
  }

   /**
   * Get leaveType
   * @return leaveType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLeaveType() {
    return leaveType;
  }


  public void setLeaveType(String leaveType) {
    
    
    
    this.leaveType = leaveType;
  }


  public PtoPolicyModel leaveYearStart(String leaveYearStart) {
    
    
    
    
    this.leaveYearStart = leaveYearStart;
    return this;
  }

   /**
   * Get leaveYearStart
   * @return leaveYearStart
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLeaveYearStart() {
    return leaveYearStart;
  }


  public void setLeaveYearStart(String leaveYearStart) {
    
    
    
    this.leaveYearStart = leaveYearStart;
  }


  public PtoPolicyModel leaveYearStartDate(LocalDate leaveYearStartDate) {
    
    
    
    
    this.leaveYearStartDate = leaveYearStartDate;
    return this;
  }

   /**
   * Get leaveYearStartDate
   * @return leaveYearStartDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LocalDate getLeaveYearStartDate() {
    return leaveYearStartDate;
  }


  public void setLeaveYearStartDate(LocalDate leaveYearStartDate) {
    
    
    
    this.leaveYearStartDate = leaveYearStartDate;
  }


  public PtoPolicyModel nextRunDate(LocalDate nextRunDate) {
    
    
    
    
    this.nextRunDate = nextRunDate;
    return this;
  }

   /**
   * Get nextRunDate
   * @return nextRunDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public LocalDate getNextRunDate() {
    return nextRunDate;
  }


  public void setNextRunDate(LocalDate nextRunDate) {
    
    
    
    this.nextRunDate = nextRunDate;
  }


  public PtoPolicyModel paid(Integer paid) {
    
    
    
    
    this.paid = paid;
    return this;
  }

   /**
   * Get paid
   * @return paid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getPaid() {
    return paid;
  }


  public void setPaid(Integer paid) {
    
    
    
    this.paid = paid;
  }


  public PtoPolicyModel policyName(String policyName) {
    
    
    
    
    this.policyName = policyName;
    return this;
  }

   /**
   * Get policyName
   * @return policyName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPolicyName() {
    return policyName;
  }


  public void setPolicyName(String policyName) {
    
    
    
    this.policyName = policyName;
  }


  public PtoPolicyModel policycondition(String policycondition) {
    
    
    
    
    this.policycondition = policycondition;
    return this;
  }

   /**
   * Get policycondition
   * @return policycondition
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPolicycondition() {
    return policycondition;
  }


  public void setPolicycondition(String policycondition) {
    
    
    
    this.policycondition = policycondition;
  }


  public PtoPolicyModel prorated(Integer prorated) {
    
    
    
    
    this.prorated = prorated;
    return this;
  }

   /**
   * Get prorated
   * @return prorated
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getProrated() {
    return prorated;
  }


  public void setProrated(Integer prorated) {
    
    
    
    this.prorated = prorated;
  }


  public PtoPolicyModel ptoPolicyApprovalFlowModel(PtoPolicyApprovalFlowModel ptoPolicyApprovalFlowModel) {
    
    
    
    
    this.ptoPolicyApprovalFlowModel = ptoPolicyApprovalFlowModel;
    return this;
  }

   /**
   * Get ptoPolicyApprovalFlowModel
   * @return ptoPolicyApprovalFlowModel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PtoPolicyApprovalFlowModel getPtoPolicyApprovalFlowModel() {
    return ptoPolicyApprovalFlowModel;
  }


  public void setPtoPolicyApprovalFlowModel(PtoPolicyApprovalFlowModel ptoPolicyApprovalFlowModel) {
    
    
    
    this.ptoPolicyApprovalFlowModel = ptoPolicyApprovalFlowModel;
  }


  public PtoPolicyModel ptoPolicyChainModel(PtoPolicyChainModel ptoPolicyChainModel) {
    
    
    
    
    this.ptoPolicyChainModel = ptoPolicyChainModel;
    return this;
  }

   /**
   * Get ptoPolicyChainModel
   * @return ptoPolicyChainModel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PtoPolicyChainModel getPtoPolicyChainModel() {
    return ptoPolicyChainModel;
  }


  public void setPtoPolicyChainModel(PtoPolicyChainModel ptoPolicyChainModel) {
    
    
    
    this.ptoPolicyChainModel = ptoPolicyChainModel;
  }


  public PtoPolicyModel ptoPolicyChainSeqId(Integer ptoPolicyChainSeqId) {
    
    
    
    
    this.ptoPolicyChainSeqId = ptoPolicyChainSeqId;
    return this;
  }

   /**
   * Get ptoPolicyChainSeqId
   * @return ptoPolicyChainSeqId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getPtoPolicyChainSeqId() {
    return ptoPolicyChainSeqId;
  }


  public void setPtoPolicyChainSeqId(Integer ptoPolicyChainSeqId) {
    
    
    
    this.ptoPolicyChainSeqId = ptoPolicyChainSeqId;
  }


  public PtoPolicyModel ptoPolicyId(Integer ptoPolicyId) {
    
    
    
    
    this.ptoPolicyId = ptoPolicyId;
    return this;
  }

   /**
   * Get ptoPolicyId
   * @return ptoPolicyId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getPtoPolicyId() {
    return ptoPolicyId;
  }


  public void setPtoPolicyId(Integer ptoPolicyId) {
    
    
    
    this.ptoPolicyId = ptoPolicyId;
  }


  public PtoPolicyModel rollOverMax(Double rollOverMax) {
    
    
    
    
    this.rollOverMax = rollOverMax;
    return this;
  }

   /**
   * Get rollOverMax
   * @return rollOverMax
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getRollOverMax() {
    return rollOverMax;
  }


  public void setRollOverMax(Double rollOverMax) {
    
    
    
    this.rollOverMax = rollOverMax;
  }


  public PtoPolicyModel rollOverPercentage(Double rollOverPercentage) {
    
    
    
    
    this.rollOverPercentage = rollOverPercentage;
    return this;
  }

   /**
   * Get rollOverPercentage
   * @return rollOverPercentage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Double getRollOverPercentage() {
    return rollOverPercentage;
  }


  public void setRollOverPercentage(Double rollOverPercentage) {
    
    
    
    this.rollOverPercentage = rollOverPercentage;
  }


  public PtoPolicyModel showInCalendar(Integer showInCalendar) {
    
    
    
    
    this.showInCalendar = showInCalendar;
    return this;
  }

   /**
   * Get showInCalendar
   * @return showInCalendar
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getShowInCalendar() {
    return showInCalendar;
  }


  public void setShowInCalendar(Integer showInCalendar) {
    
    
    
    this.showInCalendar = showInCalendar;
  }


  public PtoPolicyModel tenureThreshold(Float tenureThreshold) {
    
    
    
    
    this.tenureThreshold = tenureThreshold;
    return this;
  }

   /**
   * Get tenureThreshold
   * @return tenureThreshold
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Float getTenureThreshold() {
    return tenureThreshold;
  }


  public void setTenureThreshold(Float tenureThreshold) {
    
    
    
    this.tenureThreshold = tenureThreshold;
  }


  public PtoPolicyModel thresholdQuantity(Integer thresholdQuantity) {
    
    
    
    
    this.thresholdQuantity = thresholdQuantity;
    return this;
  }

   /**
   * Get thresholdQuantity
   * @return thresholdQuantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getThresholdQuantity() {
    return thresholdQuantity;
  }


  public void setThresholdQuantity(Integer thresholdQuantity) {
    
    
    
    this.thresholdQuantity = thresholdQuantity;
  }


  public PtoPolicyModel thresholdUnit(String thresholdUnit) {
    
    
    
    
    this.thresholdUnit = thresholdUnit;
    return this;
  }

   /**
   * Get thresholdUnit
   * @return thresholdUnit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getThresholdUnit() {
    return thresholdUnit;
  }


  public void setThresholdUnit(String thresholdUnit) {
    
    
    
    this.thresholdUnit = thresholdUnit;
  }


  public PtoPolicyModel unit(String unit) {
    
    
    
    
    this.unit = unit;
    return this;
  }

   /**
   * Get unit
   * @return unit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUnit() {
    return unit;
  }


  public void setUnit(String unit) {
    
    
    
    this.unit = unit;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the PtoPolicyModel instance itself
   */
  public PtoPolicyModel putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PtoPolicyModel ptoPolicyModel = (PtoPolicyModel) o;
    return Objects.equals(this.description, ptoPolicyModel.description) &&
        Objects.equals(this.accrualRateAnnual, ptoPolicyModel.accrualRateAnnual) &&
        Objects.equals(this.accrualRateAnnualUnit, ptoPolicyModel.accrualRateAnnualUnit) &&
        Objects.equals(this.accrualRateHours, ptoPolicyModel.accrualRateHours) &&
        Objects.equals(this.accrualRateUnit, ptoPolicyModel.accrualRateUnit) &&
        Objects.equals(this.accrualThresholdWeeks, ptoPolicyModel.accrualThresholdWeeks) &&
        Objects.equals(this.accrualTime, ptoPolicyModel.accrualTime) &&
        Objects.equals(this.accrualTimeSpan, ptoPolicyModel.accrualTimeSpan) &&
        Objects.equals(this.accrualtype, ptoPolicyModel.accrualtype) &&
        Objects.equals(this.allowAccrualRateOverride, ptoPolicyModel.allowAccrualRateOverride) &&
        Objects.equals(this.allowRequestBeyondBal, ptoPolicyModel.allowRequestBeyondBal) &&
        Objects.equals(this.applicability, ptoPolicyModel.applicability) &&
        Objects.equals(this.bonus, ptoPolicyModel.bonus) &&
        Objects.equals(this.bonusMax, ptoPolicyModel.bonusMax) &&
        Objects.equals(this.carryoverDate, ptoPolicyModel.carryoverDate) &&
        Objects.equals(this.carryoverExpirationQuantity, ptoPolicyModel.carryoverExpirationQuantity) &&
        Objects.equals(this.carryoverExpirationUnit, ptoPolicyModel.carryoverExpirationUnit) &&
        Objects.equals(this.cid, ptoPolicyModel.cid) &&
        Objects.equals(this.createUserId, ptoPolicyModel.createUserId) &&
        Objects.equals(this.createts, ptoPolicyModel.createts) &&
        Objects.equals(this.customIcon, ptoPolicyModel.customIcon) &&
        Objects.equals(this.daysDefinition, ptoPolicyModel.daysDefinition) &&
        Objects.equals(this.effectiveDate, ptoPolicyModel.effectiveDate) &&
        Objects.equals(this.expirationDate, ptoPolicyModel.expirationDate) &&
        Objects.equals(this.halfDayAllowed, ptoPolicyModel.halfDayAllowed) &&
        Objects.equals(this.hasAssignment, ptoPolicyModel.hasAssignment) &&
        Objects.equals(this.icon, ptoPolicyModel.icon) &&
        Objects.equals(this.isAccrued, ptoPolicyModel.isAccrued) &&
        Objects.equals(this.lastRun, ptoPolicyModel.lastRun) &&
        Objects.equals(this.leaveType, ptoPolicyModel.leaveType) &&
        Objects.equals(this.leaveYearStart, ptoPolicyModel.leaveYearStart) &&
        Objects.equals(this.leaveYearStartDate, ptoPolicyModel.leaveYearStartDate) &&
        Objects.equals(this.nextRunDate, ptoPolicyModel.nextRunDate) &&
        Objects.equals(this.paid, ptoPolicyModel.paid) &&
        Objects.equals(this.policyName, ptoPolicyModel.policyName) &&
        Objects.equals(this.policycondition, ptoPolicyModel.policycondition) &&
        Objects.equals(this.prorated, ptoPolicyModel.prorated) &&
        Objects.equals(this.ptoPolicyApprovalFlowModel, ptoPolicyModel.ptoPolicyApprovalFlowModel) &&
        Objects.equals(this.ptoPolicyChainModel, ptoPolicyModel.ptoPolicyChainModel) &&
        Objects.equals(this.ptoPolicyChainSeqId, ptoPolicyModel.ptoPolicyChainSeqId) &&
        Objects.equals(this.ptoPolicyId, ptoPolicyModel.ptoPolicyId) &&
        Objects.equals(this.rollOverMax, ptoPolicyModel.rollOverMax) &&
        Objects.equals(this.rollOverPercentage, ptoPolicyModel.rollOverPercentage) &&
        Objects.equals(this.showInCalendar, ptoPolicyModel.showInCalendar) &&
        Objects.equals(this.tenureThreshold, ptoPolicyModel.tenureThreshold) &&
        Objects.equals(this.thresholdQuantity, ptoPolicyModel.thresholdQuantity) &&
        Objects.equals(this.thresholdUnit, ptoPolicyModel.thresholdUnit) &&
        Objects.equals(this.unit, ptoPolicyModel.unit)&&
        Objects.equals(this.additionalProperties, ptoPolicyModel.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, accrualRateAnnual, accrualRateAnnualUnit, accrualRateHours, accrualRateUnit, accrualThresholdWeeks, accrualTime, accrualTimeSpan, accrualtype, allowAccrualRateOverride, allowRequestBeyondBal, applicability, bonus, bonusMax, carryoverDate, carryoverExpirationQuantity, carryoverExpirationUnit, cid, createUserId, createts, customIcon, daysDefinition, effectiveDate, expirationDate, halfDayAllowed, hasAssignment, icon, isAccrued, lastRun, leaveType, leaveYearStart, leaveYearStartDate, nextRunDate, paid, policyName, policycondition, prorated, ptoPolicyApprovalFlowModel, ptoPolicyChainModel, ptoPolicyChainSeqId, ptoPolicyId, rollOverMax, rollOverPercentage, showInCalendar, tenureThreshold, thresholdQuantity, thresholdUnit, unit, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PtoPolicyModel {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    accrualRateAnnual: ").append(toIndentedString(accrualRateAnnual)).append("\n");
    sb.append("    accrualRateAnnualUnit: ").append(toIndentedString(accrualRateAnnualUnit)).append("\n");
    sb.append("    accrualRateHours: ").append(toIndentedString(accrualRateHours)).append("\n");
    sb.append("    accrualRateUnit: ").append(toIndentedString(accrualRateUnit)).append("\n");
    sb.append("    accrualThresholdWeeks: ").append(toIndentedString(accrualThresholdWeeks)).append("\n");
    sb.append("    accrualTime: ").append(toIndentedString(accrualTime)).append("\n");
    sb.append("    accrualTimeSpan: ").append(toIndentedString(accrualTimeSpan)).append("\n");
    sb.append("    accrualtype: ").append(toIndentedString(accrualtype)).append("\n");
    sb.append("    allowAccrualRateOverride: ").append(toIndentedString(allowAccrualRateOverride)).append("\n");
    sb.append("    allowRequestBeyondBal: ").append(toIndentedString(allowRequestBeyondBal)).append("\n");
    sb.append("    applicability: ").append(toIndentedString(applicability)).append("\n");
    sb.append("    bonus: ").append(toIndentedString(bonus)).append("\n");
    sb.append("    bonusMax: ").append(toIndentedString(bonusMax)).append("\n");
    sb.append("    carryoverDate: ").append(toIndentedString(carryoverDate)).append("\n");
    sb.append("    carryoverExpirationQuantity: ").append(toIndentedString(carryoverExpirationQuantity)).append("\n");
    sb.append("    carryoverExpirationUnit: ").append(toIndentedString(carryoverExpirationUnit)).append("\n");
    sb.append("    cid: ").append(toIndentedString(cid)).append("\n");
    sb.append("    createUserId: ").append(toIndentedString(createUserId)).append("\n");
    sb.append("    createts: ").append(toIndentedString(createts)).append("\n");
    sb.append("    customIcon: ").append(toIndentedString(customIcon)).append("\n");
    sb.append("    daysDefinition: ").append(toIndentedString(daysDefinition)).append("\n");
    sb.append("    effectiveDate: ").append(toIndentedString(effectiveDate)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    halfDayAllowed: ").append(toIndentedString(halfDayAllowed)).append("\n");
    sb.append("    hasAssignment: ").append(toIndentedString(hasAssignment)).append("\n");
    sb.append("    icon: ").append(toIndentedString(icon)).append("\n");
    sb.append("    isAccrued: ").append(toIndentedString(isAccrued)).append("\n");
    sb.append("    lastRun: ").append(toIndentedString(lastRun)).append("\n");
    sb.append("    leaveType: ").append(toIndentedString(leaveType)).append("\n");
    sb.append("    leaveYearStart: ").append(toIndentedString(leaveYearStart)).append("\n");
    sb.append("    leaveYearStartDate: ").append(toIndentedString(leaveYearStartDate)).append("\n");
    sb.append("    nextRunDate: ").append(toIndentedString(nextRunDate)).append("\n");
    sb.append("    paid: ").append(toIndentedString(paid)).append("\n");
    sb.append("    policyName: ").append(toIndentedString(policyName)).append("\n");
    sb.append("    policycondition: ").append(toIndentedString(policycondition)).append("\n");
    sb.append("    prorated: ").append(toIndentedString(prorated)).append("\n");
    sb.append("    ptoPolicyApprovalFlowModel: ").append(toIndentedString(ptoPolicyApprovalFlowModel)).append("\n");
    sb.append("    ptoPolicyChainModel: ").append(toIndentedString(ptoPolicyChainModel)).append("\n");
    sb.append("    ptoPolicyChainSeqId: ").append(toIndentedString(ptoPolicyChainSeqId)).append("\n");
    sb.append("    ptoPolicyId: ").append(toIndentedString(ptoPolicyId)).append("\n");
    sb.append("    rollOverMax: ").append(toIndentedString(rollOverMax)).append("\n");
    sb.append("    rollOverPercentage: ").append(toIndentedString(rollOverPercentage)).append("\n");
    sb.append("    showInCalendar: ").append(toIndentedString(showInCalendar)).append("\n");
    sb.append("    tenureThreshold: ").append(toIndentedString(tenureThreshold)).append("\n");
    sb.append("    thresholdQuantity: ").append(toIndentedString(thresholdQuantity)).append("\n");
    sb.append("    thresholdUnit: ").append(toIndentedString(thresholdUnit)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("description");
    openapiFields.add("accrualRateAnnual");
    openapiFields.add("accrualRateAnnualUnit");
    openapiFields.add("accrualRateHours");
    openapiFields.add("accrualRateUnit");
    openapiFields.add("accrualThresholdWeeks");
    openapiFields.add("accrualTime");
    openapiFields.add("accrualTimeSpan");
    openapiFields.add("accrualtype");
    openapiFields.add("allowAccrualRateOverride");
    openapiFields.add("allowRequestBeyondBal");
    openapiFields.add("applicability");
    openapiFields.add("bonus");
    openapiFields.add("bonusMax");
    openapiFields.add("carryoverDate");
    openapiFields.add("carryoverExpirationQuantity");
    openapiFields.add("carryoverExpirationUnit");
    openapiFields.add("cid");
    openapiFields.add("createUserId");
    openapiFields.add("createts");
    openapiFields.add("customIcon");
    openapiFields.add("daysDefinition");
    openapiFields.add("effectiveDate");
    openapiFields.add("expirationDate");
    openapiFields.add("halfDayAllowed");
    openapiFields.add("hasAssignment");
    openapiFields.add("icon");
    openapiFields.add("isAccrued");
    openapiFields.add("lastRun");
    openapiFields.add("leaveType");
    openapiFields.add("leaveYearStart");
    openapiFields.add("leaveYearStartDate");
    openapiFields.add("nextRunDate");
    openapiFields.add("paid");
    openapiFields.add("policyName");
    openapiFields.add("policycondition");
    openapiFields.add("prorated");
    openapiFields.add("ptoPolicyApprovalFlowModel");
    openapiFields.add("ptoPolicyChainModel");
    openapiFields.add("ptoPolicyChainSeqId");
    openapiFields.add("ptoPolicyId");
    openapiFields.add("rollOverMax");
    openapiFields.add("rollOverPercentage");
    openapiFields.add("showInCalendar");
    openapiFields.add("tenureThreshold");
    openapiFields.add("thresholdQuantity");
    openapiFields.add("thresholdUnit");
    openapiFields.add("unit");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("ptoPolicyId");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PtoPolicyModel
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!PtoPolicyModel.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PtoPolicyModel is not found in the empty JSON string", PtoPolicyModel.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PtoPolicyModel.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("accrualTimeSpan") != null && !jsonObj.get("accrualTimeSpan").isJsonNull()) && !jsonObj.get("accrualTimeSpan").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `accrualTimeSpan` to be a primitive type in the JSON string but got `%s`", jsonObj.get("accrualTimeSpan").toString()));
      }
      if ((jsonObj.get("accrualtype") != null && !jsonObj.get("accrualtype").isJsonNull()) && !jsonObj.get("accrualtype").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `accrualtype` to be a primitive type in the JSON string but got `%s`", jsonObj.get("accrualtype").toString()));
      }
      if ((jsonObj.get("carryoverExpirationUnit") != null && !jsonObj.get("carryoverExpirationUnit").isJsonNull()) && !jsonObj.get("carryoverExpirationUnit").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `carryoverExpirationUnit` to be a primitive type in the JSON string but got `%s`", jsonObj.get("carryoverExpirationUnit").toString()));
      }
      // validate the optional field `createts`
      if (jsonObj.get("createts") != null && !jsonObj.get("createts").isJsonNull()) {
        Timestamp.validateJsonObject(jsonObj.getAsJsonObject("createts"));
      }
      if ((jsonObj.get("customIcon") != null && !jsonObj.get("customIcon").isJsonNull()) && !jsonObj.get("customIcon").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `customIcon` to be a primitive type in the JSON string but got `%s`", jsonObj.get("customIcon").toString()));
      }
      if ((jsonObj.get("daysDefinition") != null && !jsonObj.get("daysDefinition").isJsonNull()) && !jsonObj.get("daysDefinition").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `daysDefinition` to be a primitive type in the JSON string but got `%s`", jsonObj.get("daysDefinition").toString()));
      }
      if ((jsonObj.get("icon") != null && !jsonObj.get("icon").isJsonNull()) && !jsonObj.get("icon").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `icon` to be a primitive type in the JSON string but got `%s`", jsonObj.get("icon").toString()));
      }
      if ((jsonObj.get("isAccrued") != null && !jsonObj.get("isAccrued").isJsonNull()) && !jsonObj.get("isAccrued").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `isAccrued` to be a primitive type in the JSON string but got `%s`", jsonObj.get("isAccrued").toString()));
      }
      if ((jsonObj.get("leaveType") != null && !jsonObj.get("leaveType").isJsonNull()) && !jsonObj.get("leaveType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `leaveType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("leaveType").toString()));
      }
      if ((jsonObj.get("leaveYearStart") != null && !jsonObj.get("leaveYearStart").isJsonNull()) && !jsonObj.get("leaveYearStart").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `leaveYearStart` to be a primitive type in the JSON string but got `%s`", jsonObj.get("leaveYearStart").toString()));
      }
      if ((jsonObj.get("policyName") != null && !jsonObj.get("policyName").isJsonNull()) && !jsonObj.get("policyName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `policyName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("policyName").toString()));
      }
      if ((jsonObj.get("policycondition") != null && !jsonObj.get("policycondition").isJsonNull()) && !jsonObj.get("policycondition").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `policycondition` to be a primitive type in the JSON string but got `%s`", jsonObj.get("policycondition").toString()));
      }
      // validate the optional field `ptoPolicyApprovalFlowModel`
      if (jsonObj.get("ptoPolicyApprovalFlowModel") != null && !jsonObj.get("ptoPolicyApprovalFlowModel").isJsonNull()) {
        PtoPolicyApprovalFlowModel.validateJsonObject(jsonObj.getAsJsonObject("ptoPolicyApprovalFlowModel"));
      }
      // validate the optional field `ptoPolicyChainModel`
      if (jsonObj.get("ptoPolicyChainModel") != null && !jsonObj.get("ptoPolicyChainModel").isJsonNull()) {
        PtoPolicyChainModel.validateJsonObject(jsonObj.getAsJsonObject("ptoPolicyChainModel"));
      }
      if ((jsonObj.get("thresholdUnit") != null && !jsonObj.get("thresholdUnit").isJsonNull()) && !jsonObj.get("thresholdUnit").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `thresholdUnit` to be a primitive type in the JSON string but got `%s`", jsonObj.get("thresholdUnit").toString()));
      }
      if ((jsonObj.get("unit") != null && !jsonObj.get("unit").isJsonNull()) && !jsonObj.get("unit").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `unit` to be a primitive type in the JSON string but got `%s`", jsonObj.get("unit").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PtoPolicyModel.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PtoPolicyModel' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PtoPolicyModel> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PtoPolicyModel.class));

       return (TypeAdapter<T>) new TypeAdapter<PtoPolicyModel>() {
           @Override
           public void write(JsonWriter out, PtoPolicyModel value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public PtoPolicyModel read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             PtoPolicyModel instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PtoPolicyModel given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PtoPolicyModel
  * @throws IOException if the JSON string is invalid with respect to PtoPolicyModel
  */
  public static PtoPolicyModel fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PtoPolicyModel.class);
  }

 /**
  * Convert an instance of PtoPolicyModel to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

