/*
 * Expense Reports
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * SkillsCreateNewSkillRequestSkillTypeModel
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class SkillsCreateNewSkillRequestSkillTypeModel {
  public static final String SERIALIZED_NAME_CREATE_USER_ID = "createUserId";
  @SerializedName(SERIALIZED_NAME_CREATE_USER_ID)
  private Integer createUserId;

  public static final String SERIALIZED_NAME_SKILL_TYPE_DESC = "skillTypeDesc";
  @SerializedName(SERIALIZED_NAME_SKILL_TYPE_DESC)
  private String skillTypeDesc;

  public static final String SERIALIZED_NAME_SKILL_TYPE_ID = "skillTypeId";
  @SerializedName(SERIALIZED_NAME_SKILL_TYPE_ID)
  private Integer skillTypeId;

  public static final String SERIALIZED_NAME_SKILL_TYPE_NAME = "skillTypeName";
  @SerializedName(SERIALIZED_NAME_SKILL_TYPE_NAME)
  private String skillTypeName;

  public SkillsCreateNewSkillRequestSkillTypeModel() {
  }

  public SkillsCreateNewSkillRequestSkillTypeModel createUserId(Integer createUserId) {
    
    
    
    
    this.createUserId = createUserId;
    return this;
  }

   /**
   * The ID of the user who is creating skill.
   * @return createUserId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the user who is creating skill.")

  public Integer getCreateUserId() {
    return createUserId;
  }


  public void setCreateUserId(Integer createUserId) {
    
    
    
    this.createUserId = createUserId;
  }


  public SkillsCreateNewSkillRequestSkillTypeModel skillTypeDesc(String skillTypeDesc) {
    
    
    
    
    this.skillTypeDesc = skillTypeDesc;
    return this;
  }

   /**
   * Description of the skill type.
   * @return skillTypeDesc
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Description of the skill type.")

  public String getSkillTypeDesc() {
    return skillTypeDesc;
  }


  public void setSkillTypeDesc(String skillTypeDesc) {
    
    
    
    this.skillTypeDesc = skillTypeDesc;
  }


  public SkillsCreateNewSkillRequestSkillTypeModel skillTypeId(Integer skillTypeId) {
    
    
    
    
    this.skillTypeId = skillTypeId;
    return this;
  }

   /**
   * The ID of the assessment scale.
   * @return skillTypeId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The ID of the assessment scale.")

  public Integer getSkillTypeId() {
    return skillTypeId;
  }


  public void setSkillTypeId(Integer skillTypeId) {
    
    
    
    this.skillTypeId = skillTypeId;
  }


  public SkillsCreateNewSkillRequestSkillTypeModel skillTypeName(String skillTypeName) {
    
    
    
    
    this.skillTypeName = skillTypeName;
    return this;
  }

   /**
   * Name of the skill type.
   * @return skillTypeName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Name of the skill type.")

  public String getSkillTypeName() {
    return skillTypeName;
  }


  public void setSkillTypeName(String skillTypeName) {
    
    
    
    this.skillTypeName = skillTypeName;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the SkillsCreateNewSkillRequestSkillTypeModel instance itself
   */
  public SkillsCreateNewSkillRequestSkillTypeModel putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SkillsCreateNewSkillRequestSkillTypeModel skillsCreateNewSkillRequestSkillTypeModel = (SkillsCreateNewSkillRequestSkillTypeModel) o;
    return Objects.equals(this.createUserId, skillsCreateNewSkillRequestSkillTypeModel.createUserId) &&
        Objects.equals(this.skillTypeDesc, skillsCreateNewSkillRequestSkillTypeModel.skillTypeDesc) &&
        Objects.equals(this.skillTypeId, skillsCreateNewSkillRequestSkillTypeModel.skillTypeId) &&
        Objects.equals(this.skillTypeName, skillsCreateNewSkillRequestSkillTypeModel.skillTypeName)&&
        Objects.equals(this.additionalProperties, skillsCreateNewSkillRequestSkillTypeModel.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createUserId, skillTypeDesc, skillTypeId, skillTypeName, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SkillsCreateNewSkillRequestSkillTypeModel {\n");
    sb.append("    createUserId: ").append(toIndentedString(createUserId)).append("\n");
    sb.append("    skillTypeDesc: ").append(toIndentedString(skillTypeDesc)).append("\n");
    sb.append("    skillTypeId: ").append(toIndentedString(skillTypeId)).append("\n");
    sb.append("    skillTypeName: ").append(toIndentedString(skillTypeName)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("createUserId");
    openapiFields.add("skillTypeDesc");
    openapiFields.add("skillTypeId");
    openapiFields.add("skillTypeName");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("skillTypeId");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to SkillsCreateNewSkillRequestSkillTypeModel
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!SkillsCreateNewSkillRequestSkillTypeModel.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SkillsCreateNewSkillRequestSkillTypeModel is not found in the empty JSON string", SkillsCreateNewSkillRequestSkillTypeModel.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SkillsCreateNewSkillRequestSkillTypeModel.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if ((jsonObj.get("skillTypeDesc") != null && !jsonObj.get("skillTypeDesc").isJsonNull()) && !jsonObj.get("skillTypeDesc").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `skillTypeDesc` to be a primitive type in the JSON string but got `%s`", jsonObj.get("skillTypeDesc").toString()));
      }
      if ((jsonObj.get("skillTypeName") != null && !jsonObj.get("skillTypeName").isJsonNull()) && !jsonObj.get("skillTypeName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `skillTypeName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("skillTypeName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SkillsCreateNewSkillRequestSkillTypeModel.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SkillsCreateNewSkillRequestSkillTypeModel' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SkillsCreateNewSkillRequestSkillTypeModel> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SkillsCreateNewSkillRequestSkillTypeModel.class));

       return (TypeAdapter<T>) new TypeAdapter<SkillsCreateNewSkillRequestSkillTypeModel>() {
           @Override
           public void write(JsonWriter out, SkillsCreateNewSkillRequestSkillTypeModel value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public SkillsCreateNewSkillRequestSkillTypeModel read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             SkillsCreateNewSkillRequestSkillTypeModel instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SkillsCreateNewSkillRequestSkillTypeModel given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SkillsCreateNewSkillRequestSkillTypeModel
  * @throws IOException if the JSON string is invalid with respect to SkillsCreateNewSkillRequestSkillTypeModel
  */
  public static SkillsCreateNewSkillRequestSkillTypeModel fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SkillsCreateNewSkillRequestSkillTypeModel.class);
  }

 /**
  * Convert an instance of SkillsCreateNewSkillRequestSkillTypeModel to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

