/*
 * Expense Reports
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.WorkflowParameterModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * WorkflowParameterAssignmentModel
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class WorkflowParameterAssignmentModel {
  public static final String SERIALIZED_NAME_CID = "cid";
  @SerializedName(SERIALIZED_NAME_CID)
  private Integer cid;

  public static final String SERIALIZED_NAME_PARAM_NAME = "paramName";
  @SerializedName(SERIALIZED_NAME_PARAM_NAME)
  private String paramName;

  public static final String SERIALIZED_NAME_PARAM_VALUE = "paramValue";
  @SerializedName(SERIALIZED_NAME_PARAM_VALUE)
  private String paramValue;

  public static final String SERIALIZED_NAME_PARAMETER_MODEL = "parameterModel";
  @SerializedName(SERIALIZED_NAME_PARAMETER_MODEL)
  private WorkflowParameterModel parameterModel;

  public static final String SERIALIZED_NAME_USER_WORKFLOWID = "userWorkflowid";
  @SerializedName(SERIALIZED_NAME_USER_WORKFLOWID)
  private Integer userWorkflowid;

  public static final String SERIALIZED_NAME_WA_PARAM_ID = "waParamId";
  @SerializedName(SERIALIZED_NAME_WA_PARAM_ID)
  private Integer waParamId;

  public static final String SERIALIZED_NAME_WORKFLOW_ARG_ID = "workflowArgId";
  @SerializedName(SERIALIZED_NAME_WORKFLOW_ARG_ID)
  private Integer workflowArgId;

  public WorkflowParameterAssignmentModel() {
  }

  public WorkflowParameterAssignmentModel cid(Integer cid) {
    
    
    
    
    this.cid = cid;
    return this;
  }

   /**
   * Get cid
   * @return cid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getCid() {
    return cid;
  }


  public void setCid(Integer cid) {
    
    
    
    this.cid = cid;
  }


  public WorkflowParameterAssignmentModel paramName(String paramName) {
    
    
    
    
    this.paramName = paramName;
    return this;
  }

   /**
   * Get paramName
   * @return paramName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getParamName() {
    return paramName;
  }


  public void setParamName(String paramName) {
    
    
    
    this.paramName = paramName;
  }


  public WorkflowParameterAssignmentModel paramValue(String paramValue) {
    
    
    
    
    this.paramValue = paramValue;
    return this;
  }

   /**
   * Get paramValue
   * @return paramValue
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getParamValue() {
    return paramValue;
  }


  public void setParamValue(String paramValue) {
    
    
    
    this.paramValue = paramValue;
  }


  public WorkflowParameterAssignmentModel parameterModel(WorkflowParameterModel parameterModel) {
    
    
    
    
    this.parameterModel = parameterModel;
    return this;
  }

   /**
   * Get parameterModel
   * @return parameterModel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public WorkflowParameterModel getParameterModel() {
    return parameterModel;
  }


  public void setParameterModel(WorkflowParameterModel parameterModel) {
    
    
    
    this.parameterModel = parameterModel;
  }


  public WorkflowParameterAssignmentModel userWorkflowid(Integer userWorkflowid) {
    
    
    
    
    this.userWorkflowid = userWorkflowid;
    return this;
  }

   /**
   * Get userWorkflowid
   * @return userWorkflowid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getUserWorkflowid() {
    return userWorkflowid;
  }


  public void setUserWorkflowid(Integer userWorkflowid) {
    
    
    
    this.userWorkflowid = userWorkflowid;
  }


  public WorkflowParameterAssignmentModel waParamId(Integer waParamId) {
    
    
    
    
    this.waParamId = waParamId;
    return this;
  }

   /**
   * Get waParamId
   * @return waParamId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getWaParamId() {
    return waParamId;
  }


  public void setWaParamId(Integer waParamId) {
    
    
    
    this.waParamId = waParamId;
  }


  public WorkflowParameterAssignmentModel workflowArgId(Integer workflowArgId) {
    
    
    
    
    this.workflowArgId = workflowArgId;
    return this;
  }

   /**
   * Get workflowArgId
   * @return workflowArgId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getWorkflowArgId() {
    return workflowArgId;
  }


  public void setWorkflowArgId(Integer workflowArgId) {
    
    
    
    this.workflowArgId = workflowArgId;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the WorkflowParameterAssignmentModel instance itself
   */
  public WorkflowParameterAssignmentModel putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowParameterAssignmentModel workflowParameterAssignmentModel = (WorkflowParameterAssignmentModel) o;
    return Objects.equals(this.cid, workflowParameterAssignmentModel.cid) &&
        Objects.equals(this.paramName, workflowParameterAssignmentModel.paramName) &&
        Objects.equals(this.paramValue, workflowParameterAssignmentModel.paramValue) &&
        Objects.equals(this.parameterModel, workflowParameterAssignmentModel.parameterModel) &&
        Objects.equals(this.userWorkflowid, workflowParameterAssignmentModel.userWorkflowid) &&
        Objects.equals(this.waParamId, workflowParameterAssignmentModel.waParamId) &&
        Objects.equals(this.workflowArgId, workflowParameterAssignmentModel.workflowArgId)&&
        Objects.equals(this.additionalProperties, workflowParameterAssignmentModel.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cid, paramName, paramValue, parameterModel, userWorkflowid, waParamId, workflowArgId, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowParameterAssignmentModel {\n");
    sb.append("    cid: ").append(toIndentedString(cid)).append("\n");
    sb.append("    paramName: ").append(toIndentedString(paramName)).append("\n");
    sb.append("    paramValue: ").append(toIndentedString(paramValue)).append("\n");
    sb.append("    parameterModel: ").append(toIndentedString(parameterModel)).append("\n");
    sb.append("    userWorkflowid: ").append(toIndentedString(userWorkflowid)).append("\n");
    sb.append("    waParamId: ").append(toIndentedString(waParamId)).append("\n");
    sb.append("    workflowArgId: ").append(toIndentedString(workflowArgId)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("cid");
    openapiFields.add("paramName");
    openapiFields.add("paramValue");
    openapiFields.add("parameterModel");
    openapiFields.add("userWorkflowid");
    openapiFields.add("waParamId");
    openapiFields.add("workflowArgId");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to WorkflowParameterAssignmentModel
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!WorkflowParameterAssignmentModel.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WorkflowParameterAssignmentModel is not found in the empty JSON string", WorkflowParameterAssignmentModel.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("paramName") != null && !jsonObj.get("paramName").isJsonNull()) && !jsonObj.get("paramName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `paramName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("paramName").toString()));
      }
      if ((jsonObj.get("paramValue") != null && !jsonObj.get("paramValue").isJsonNull()) && !jsonObj.get("paramValue").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `paramValue` to be a primitive type in the JSON string but got `%s`", jsonObj.get("paramValue").toString()));
      }
      // validate the optional field `parameterModel`
      if (jsonObj.get("parameterModel") != null && !jsonObj.get("parameterModel").isJsonNull()) {
        WorkflowParameterModel.validateJsonObject(jsonObj.getAsJsonObject("parameterModel"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WorkflowParameterAssignmentModel.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WorkflowParameterAssignmentModel' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WorkflowParameterAssignmentModel> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WorkflowParameterAssignmentModel.class));

       return (TypeAdapter<T>) new TypeAdapter<WorkflowParameterAssignmentModel>() {
           @Override
           public void write(JsonWriter out, WorkflowParameterAssignmentModel value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public WorkflowParameterAssignmentModel read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             WorkflowParameterAssignmentModel instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of WorkflowParameterAssignmentModel given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of WorkflowParameterAssignmentModel
  * @throws IOException if the JSON string is invalid with respect to WorkflowParameterAssignmentModel
  */
  public static WorkflowParameterAssignmentModel fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WorkflowParameterAssignmentModel.class);
  }

 /**
  * Convert an instance of WorkflowParameterAssignmentModel to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

