/*
 * Expense Reports
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.DocumentLibraryGetDocumentAsByteArrayResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DocumentLibraryApi
 */
@Disabled
public class DocumentLibraryApiTest {

    private static DocumentLibraryApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new DocumentLibraryApi(apiClient);
    }

    /**
     * Retrieve attachments within document library
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getAttachmentsTest() throws ApiException {
        String response = api.getAttachments()
                .execute();
        // TODO: test validations
    }

    /**
     * Retrieve document as byte array
     *
     * 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDocumentAsByteArrayTest() throws ApiException {
        String fileName = null;
        DocumentLibraryGetDocumentAsByteArrayResponse response = api.getDocumentAsByteArray(fileName)
                .execute();
        // TODO: test validations
    }

}
