/*
 * Expense Reports
 * API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ShiftsApi
 */
@Disabled
public class ShiftsApiTest {

    private static ShiftsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ShiftsApi(apiClient);
    }

    /**
     * Get Shifts
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listShiftsUsingGETTest() throws ApiException {
        Integer projectId = null;
        String startDate = null;
        String endDate = null;
        String status = null;
        Object response = api.listShiftsUsingGET()
                .projectId(projectId)
                .startDate(startDate)
                .endDate(endDate)
                .status(status)
                .execute();
        // TODO: test validations
    }

    /**
     * Save Shift
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void saveShiftTest() throws ApiException {
        Object response = api.saveShift()
                .execute();
        // TODO: test validations
    }

}
